### ISSUE TITLE
number of choices in the enumeration list is incorrect

### ISSUE THREAD

**Issue by chenjunjie1994** [minerllabs/minerl#101]
As stated in the documentation,  there should be 8 and 6 choices in these two lists
========================
"nearbyCraft": "Enum(none,wooden_axe,wooden_pickaxe,stone_axe,stone_pickaxe,iron_pickaxe,crafting_table,furnace)",
"place": "Enum(none,dirt,stone,crafting_table,furnace,torch)",
========================

But can you please double check these two data structures ? when setting action['nearbyCraft'] = 7, it reports "out of range error".

**Comment by TimZF** [comment]
yeah noticed the same the "crafting table" seems to be moved out of nearbyCraft and into craft which makes sense but the docs show it wrong.

**Comment by MadcowD** [comment]
Fixed on the docs.
