### ISSUE TITLE
errors after updating to v-0.1.15

### ISSUE THREAD

**Issue by chenjunjie1994** [minerllabs/minerl#103]
I update to this version and run

>>> env=gym.make("MineRLObtainDiamond-v0")
>>> obs, _ = env.reset()

It keeps outputing these . Seems it failed to connect to some server …
Actually, I want to know if it can be run off line ?

E0626 19:13:30.498780 8168 malmo.py:403] [19:13:30] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:31.534238 8168 malmo.py:403] [19:13:31] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:32.558932 8168 malmo.py:403] [19:13:32] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:33.578072 8168 malmo.py:403] [19:13:33] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:34.596228 8168 malmo.py:403] [19:13:34] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:35.614187 8168 malmo.py:403] [19:13:35] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:36.631268 8168 malmo.py:403] [19:13:36] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:37.644524 8168 malmo.py:403] [19:13:37] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:38.658740 8168 malmo.py:403] [19:13:38] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:39.671745 8168 malmo.py:403] [19:13:39] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:40.695851 8168 malmo.py:403] [19:13:40] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:41.708018 8168 malmo.py:403] [19:13:41] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:42.719934 8168 malmo.py:403] [19:13:42] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:43.730622 8168 malmo.py:403] [19:13:43] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:44.740869 8168 malmo.py:403] [19:13:44] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:45.754959 8168 malmo.py:403] [19:13:45] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:46.770500 8168 malmo.py:403] [19:13:46] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:47.780838 8168 malmo.py:403] [19:13:47] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.
E0626 19:13:48.791393 8168 malmo.py:403] [19:13:48] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOERRORcvc-complex-type.2.3: Element ‘ServerInitialConditions’ cannot have character [children], because the type’s content type is element-only.

**Comment by MadcowD** [comment]
Fixed!

**Comment by chenjunjie1994** [comment]
> Fixed!
@MadcowD 
Hi, can you release the latest version so that I can update my current version and try?

**Comment by MadcowD** [comment]
@chenjunjie1994 
```
pip3 install --upgrade minerl
```
Try it now!
