### ISSUE TITLE
Cobblestone acquisition not being tracked in dataset?

### ISSUE THREAD

**Issue by MadcowD** [minerllabs/minerl#105]
> 
> ahh I see, and cobblestone is not tracked in the inventory, thank you. Sorry am new to minecraft

![image](https://user-images.githubusercontent.com/719535/60288887-dd8a3880-98b0-11e9-8544-38ac39a59cf5.png)

**Comment by brandonhoughton** [comment]
As of current master cobblestone is tracked in inventory dict observation for obtain tasks:
...
        'stone': spaces.Box(low=0, high=2304, shape=(), dtype=np.int),
        **'cobblestone': spaces.Box(low=0, high=2304, shape=(), dtype=np.int),**
        'furnace': spaces.Box(low=0, high=2304, shape=(), dtype=np.int),
        'stone_axe': spaces.Box(low=0, high=2304, shape=(), dtype=np.int),
...
