### ISSUE TITLE
error when I first attempt to create the environment with env = gym.make('MineRLNavigateDense-v0')

### ISSUE THREAD

**Issue by neckercube** [minerllabs/minerl#117]
I encountered this error when I first attempt to create the environment with env = gym.make('MineRLNavigateDense-v0')

ERROR:minerl.env.malmo:FAILURE: Build failed with an exception.
ERROR:minerl.env.malmo:
ERROR:minerl.env.malmo:* Where:
ERROR:minerl.env.malmo:Build file '/private/var/folders/jj/dmfy2np55gs320cs69sl4sk80000gn/T/tmprhng8039/Minecraft/build.gradle' line: 187
ERROR:minerl.env.malmo:
ERROR:minerl.env.malmo:* What went wrong:
ERROR:minerl.env.malmo:Execution failed for task ':compileJava'.
ERROR:minerl.env.malmo:> [B cannot be cast to [C

I'm using mac, python3.7.3 Anaconda.
Does anyone have a clue on how to fix this?

Attaching full error log
[minecraft.log](https://github.com/minerllabs/minerl/files/3343302/minecraft.log)

**Comment by MadcowD** [comment]
This is related to https://stackoverflow.com/questions/46006686/illegal-reflective-access-operation

You are using the wrong version of Java (Java 9) where you should be using JDK 8. Even if you follow the JDK 8 installation instructions on http://minerl.io/docs/ you'll need to either set you `JAVA_HOME` or uninstall existing java installations.

Thanks,
Will

**Comment by neckercube** [comment]
Setting correct JAVA_HOME fixed the issue. Thank you!

https://gist.github.com/schnell18/bcb9833f725be22f6acd01f94b486392
