### ISSUE TITLE
Action space in 'MineRLObtainIronAxe-v0' and MineRLObtainIronAxeDense-v0'

### ISSUE THREAD

**Issue by christoph-boesch** [minerllabs/minerl#122]
What is the point of the action equip: air in the tasks  'MineRLObtainIronAxe-v0' and MineRLObtainIronAxeDense-v0'?

**Comment by MadcowD** [comment]
Some expert trajectories unequip items (the same thing as equipping air). Hence we've added this as an action takeable by the agent.
