### ISSUE TITLE
Connection timed out.

### ISSUE THREAD

**Issue by shadowyzy** [minerllabs/minerl#124]
My code is
```
import minerl
import gym
import logging
logging.basicConfig(level=logging.DEBUG)

env = gym.make('MineRLNavigateDense-v0')
obs, _ = env.reset()
```
It seems that I can't connect the server.
It runs very slow. How to fix that problem?

> (minerl_env) ➜  minerl xvfb-run python test.py
INFO:minerl.env.malmo.instance.635bde:Starting Minecraft process: ['/tmp/tmp8l5a19hd/Minecraft/launchClient.sh', '-port', '9001', '-env', '-runDir', '/tmp/tmp8l5a19hd/Minecraft/run']
INFO:minerl.env.malmo.instance.635bde:Starting process watcher for process 23857 @ localhost:9001
DEBUG:minerl.env.malmo.instance.635bde:Downloading https://services.gradle.org/distributions/gradle-2.14-bin.zip
DEBUG:minerl.env.malmo.instance.635bde:
DEBUG:minerl.env.malmo.instance.635bde:Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
DEBUG:minerl.env.malmo.instance.635bde:	at java.net.PlainSocketImpl.socketConnect(Native Method)
DEBUG:minerl.env.malmo.instance.635bde:	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
DEBUG:minerl.env.malmo.instance.635bde:	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
DEBUG:minerl.env.malmo.instance.635bde:	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
DEBUG:minerl.env.malmo.instance.635bde:	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
DEBUG:minerl.env.malmo.instance.635bde:	at java.net.Socket.connect(Socket.java:589)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
DEBUG:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
DEBUG:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
DEBUG:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.Download.download(Download.java:44)
DEBUG:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.Install$1.call(Install.java:59)
DEBUG:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.Install$1.call(Install.java:46)
DEBUG:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
DEBUG:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.Install.createDist(Install.java:46)
DEBUG:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
DEBUG:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
ERROR:minerl.env.malmo.instance.635bde:Downloading https://services.gradle.org/distributions/gradle-2.14-bin.zip
ERROR:minerl.env.malmo.instance.635bde:
ERROR:minerl.env.malmo.instance.635bde:Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
ERROR:minerl.env.malmo.instance.635bde:	at java.net.PlainSocketImpl.socketConnect(Native Method)
ERROR:minerl.env.malmo.instance.635bde:	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
ERROR:minerl.env.malmo.instance.635bde:	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
ERROR:minerl.env.malmo.instance.635bde:	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
ERROR:minerl.env.malmo.instance.635bde:	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
ERROR:minerl.env.malmo.instance.635bde:	at java.net.Socket.connect(Socket.java:589)
ERROR:minerl.env.malmo.instance.635bde:	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
ERROR:minerl.env.malmo.instance.635bde:	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
ERROR:minerl.env.malmo.instance.635bde:	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
ERROR:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
ERROR:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.Download.download(Download.java:44)
ERROR:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.Install$1.call(Install.java:59)
ERROR:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.Install$1.call(Install.java:46)
ERROR:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
ERROR:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.Install.createDist(Install.java:46)
ERROR:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
ERROR:minerl.env.malmo.instance.635bde:	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    env = gym.make('MineRLNavigateDense-v0')
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/minerl/env/core.py", line 132, in __init__
    self.instance = self._get_new_instance(port)
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/minerl/env/core.py", line 154, in _get_new_instance
    instance.launch()
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/minerl/env/malmo.py", line 397, in launch
    raise EOFError(error_str + "\n\nMinecraft process finished unexpectedly. There was an error with Malmo.")
EOFError: Downloading https://services.gradle.org/distributions/gradle-2.14-bin.zip

> Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:59)
	at org.gradle.wrapper.Install$1.call(Install.java:46)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:46)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

Minecraft process finished unexpectedly. There was an error with Malmo.

**Comment by MadcowD** [comment]
Is that machine connected to the internet? Are there proxies that block certain websited etc?

Internet is required to finish the build process!

**Comment by MadcowD** [comment]
@shadowyzy  Just following up here. I will close this issue in a couple of days assuming that you figured out why the machine you're using can't connect to the gradle servers.

**Comment by shadowyzy** [comment]
It's really a network problem. But it's hard to solve due to some reason in the server.
I want to download the environment locally, and then upload to the server.
So, which files do I need to download and where to upload?

**Comment by MadcowD** [comment]
hmm, I'm actually still trying to figure out how to make the build process local, this might take a couple of weeks however. We didnt anticipate people having network problems at this scale :/

I will keep you posted!

**Comment by shadowyzy** [comment]
Thanks for the reply.
I fixed the network problem. Now I can curl this website.
But there will still be the above error

curl

```
(minerl_env) ➜  ~ curl https://services.gradle.org
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Gradle Services</title>
<script src="/cdn-cgi/apps/head/zmmHCWWiIZ8eWNXY8w-TWeCQJEI.js"></script><link rel="stylesheet" href="https://assets.gradle.com/lato/css/lato-font.css">
<link rel="stylesheet" href="/style.css">
<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-4207603-1', 'auto', {
        'allowLinker': true
      });
      ga('require', 'linker');
      ga('linker:autoLink', ['gradle.com', 'gradle.org'], false, true);
      ga('set', 'transport', 'beacon');
      ga('send', 'pageview');
    </script>
<script type="text/javascript">
      piAId = '69052';
      piCId = '2332';
      (function() {
        function async_load() {
          var s = document.createElement('script'); s.type = 'text/javascript';
          s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js';
          var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);
        }
        if(window.attachEvent) { window.attachEvent('onload', async_load); }
        else { window.addEventListener('load', async_load, false); }
      })();
    </script>
</head>
<body>
<div id="header">
<img src="/images/gradle.svg" />
</div>
<div id="contents">
<div class="breadcrumb">
<ul>
<li><a href="/"> services.gradle.org</a>/</li>
</ul>
</div>
<ul class="services"><li><a href="/distributions">Distributions</a></li><li><a href="/distributions-snapshots">Distributions Snapshots</a></li><li><a href="/versions">Version Information</a></li><li><a href="/fixed-issues">Issues Fixed In Version</a></li><li><a href="/known-issues">Known Issues Of Version</a></li></ul>
</div>
</body>
</html>%              

```

error

```
(minerl_env) ➜  ~ xvfb-run python minerl/test.py 
INFO:minerl.env.malmo.instance.80f87b:Starting Minecraft process: ['/tmp/tmpm6uoio_0/Minecraft/launchClient.sh', '-port', '9001', '-env', '-runDir', '/tmp/tmpm6uoio_0/Minecraft/run']
INFO:minerl.env.malmo.instance.80f87b:Starting process watcher for process 27054 @ localhost:9001
DEBUG:minerl.env.malmo.instance.80f87b:Downloading https://services.gradle.org/distributions/gradle-2.14-bin.zip
DEBUG:minerl.env.malmo.instance.80f87b:
DEBUG:minerl.env.malmo.instance.80f87b:Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
DEBUG:minerl.env.malmo.instance.80f87b:	at java.net.PlainSocketImpl.socketConnect(Native Method)
DEBUG:minerl.env.malmo.instance.80f87b:	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
DEBUG:minerl.env.malmo.instance.80f87b:	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
DEBUG:minerl.env.malmo.instance.80f87b:	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
DEBUG:minerl.env.malmo.instance.80f87b:	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
DEBUG:minerl.env.malmo.instance.80f87b:	at java.net.Socket.connect(Socket.java:589)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
DEBUG:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
DEBUG:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
DEBUG:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.Download.download(Download.java:44)
DEBUG:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.Install$1.call(Install.java:59)
DEBUG:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.Install$1.call(Install.java:46)
DEBUG:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
DEBUG:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.Install.createDist(Install.java:46)
DEBUG:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
DEBUG:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
ERROR:minerl.env.malmo.instance.80f87b:Downloading https://services.gradle.org/distributions/gradle-2.14-bin.zip
ERROR:minerl.env.malmo.instance.80f87b:
ERROR:minerl.env.malmo.instance.80f87b:Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
ERROR:minerl.env.malmo.instance.80f87b:	at java.net.PlainSocketImpl.socketConnect(Native Method)
ERROR:minerl.env.malmo.instance.80f87b:	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
ERROR:minerl.env.malmo.instance.80f87b:	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
ERROR:minerl.env.malmo.instance.80f87b:	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
ERROR:minerl.env.malmo.instance.80f87b:	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
ERROR:minerl.env.malmo.instance.80f87b:	at java.net.Socket.connect(Socket.java:589)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
ERROR:minerl.env.malmo.instance.80f87b:	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
ERROR:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
ERROR:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.Download.download(Download.java:44)
ERROR:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.Install$1.call(Install.java:59)
ERROR:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.Install$1.call(Install.java:46)
ERROR:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
ERROR:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.Install.createDist(Install.java:46)
ERROR:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
ERROR:minerl.env.malmo.instance.80f87b:	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Traceback (most recent call last):
  File "minerl/test.py", line 7, in <module>
    env = gym.make('MineRLNavigateDense-v0')
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/minerl/env/core.py", line 132, in __init__
    self.instance = self._get_new_instance(port)
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/minerl/env/core.py", line 154, in _get_new_instance
    instance.launch()
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/minerl/env/malmo.py", line 397, in launch
    raise EOFError(error_str + "\n\nMinecraft process finished unexpectedly. There was an error with Malmo.")
EOFError: Downloading https://services.gradle.org/distributions/gradle-2.14-bin.zip

Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:59)
	at org.gradle.wrapper.Install$1.call(Install.java:46)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:46)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)


Minecraft process finished unexpectedly. There was an error with Malmo.
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

(minerl_env) ➜  ~ Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/minerl/env/malmo.py", line 257, in _process_watcher
    InstanceManager._reap_process_and_children(child)
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/minerl/env/malmo.py", line 278, in _reap_process_and_children
    procs = process.children() + [process]
  File "/home/yuziyi/minerl_env/lib/python3.5/site-packages/psutil/__init__.py", line 391, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=27054)
```

**Comment by shadowyzy** [comment]
I fixed the network problem. But it still has the same error.
I am sure that it is not a problem with the local network.
I checked local network many times and it works well.
Could you check it again? @MadcowD

**Comment by shadowyzy** [comment]
Could you provide a ubantu docker with equipped environment? @MadcowD

**Comment by MadcowD** [comment]
@shadowyzy  Apologies. Yes I am working on this!

**Comment by brandonhoughton** [comment]
Closing because stale - please reopen if issue persists
