### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by Alestainer** [minerllabs/minerl#126]
When try:

`minerl.data.download("/my/path")`

get

> SSLError: HTTPSConnectionPool(host='router.sneakywines.me', port=443): Max retries exceeded with url: /minerl/data_texture_0_low_res.md5 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1056)')))

**Comment by juliusfrost** [comment]
Same here

**Comment by shadowyzy** [comment]
Same here. 
How to fix it?

**Comment by brandonhoughton** [comment]
Fixed! Thank you for bringing this to our attention
