### ISSUE TITLE
Scores exceeding the 64 reward threshold in Treechop and extra frames

### ISSUE THREAD

**Issue by marioyc** [minerllabs/minerl#127]
There are a few scores above the 64 points threshold, is this expected?

For example the highest scoring player `r2g1excellent_pluot_behemoth-11_54258-56844` gets 67 points after getting 5 points simultaneously towards the end of the video.

Also, there are a few extra frames after he achieves this score, is this also expected?

**Comment by brandonhoughton** [comment]
That's

**Comment by marioyc** [comment]
https://gist.github.com/marioyc/45d74aa7313ee945c5cbec85f94a7450

These ones have over 100 extra frames:

r2g1excellent_pluot_behemoth-11_56888-59876
r2g1excellent_pluot_behemoth-21_311-3838
r2g1equal_olive_chimera-6_7294-10110
r2g1little_salsify_djinn-7_14948-19547
r2g1equal_olive_chimera-6_10120-13553
r2g1familiar_endive_ghost-2_613-2947
r2g1absolute_grape_changeling-17_7866-10600
r2g1juvenile_apple_angel-7_113707-115804
r2g1absolute_grape_changeling-17_4927-7527
r2g1excellent_pluot_behemoth-11_26965-29520
r2g1subtle_iceberg_lettuce_nymph-6_9809-11841
r2g1tempting_capers_shapeshifter-14_12243-16213
r2g1poised_radicchio_titan-8_960-6126
r2g1excellent_pluot_behemoth-11_13750-16945
r2g1cool_sweet_potato_nymph-13_724-5562
r2g1virtuous_mustard_greens_raven_spirit-8_15578-19312
r2g1absolute_zucchini_basilisk-13_161-3515
r2g1juvenile_apple_angel-7_134699-137029
