### ISSUE TITLE
Fixing environment random seed

### ISSUE THREAD

**Issue by tomsilver** [minerllabs/minerl#14]
Thanks very much for putting together this environment!

I noticed that seeding the environment is not yet supported:
https://github.com/minerllabs/minerl/blob/master/minerl/env/core.py#L445

I was just wondering if there is any plan in the near-term to implement this.

Thanks again!

**Comment by MadcowD** [comment]
Done! We'll have this out on the next version of MineRL ;)

**Comment by tomsilver** [comment]
Awesome, thank you @MadcowD !

**Comment by MadcowD** [comment]
:) :) :)

**Comment by tomsilver** [comment]
Hey @MadcowD thanks again for looking into this. I was trying out your seed test just now, and it works as expected with seed 22, but then I tried with seed 0 and I'm seeing different initial states after each reset. Let me know if you see the same behavior or if the issue is on my end. (Hopefully it's me! Sorry to be the bearer of bad news otherwise.) Thanks!

**Comment by tomsilver** [comment]
Ah, fortunately I think this is just a small bug that only affects seed 0, bsaed on this line: https://github.com/minerllabs/minerl/blob/master/minerl/env/core.py#L683 I'll open a PR to fix.

**Comment by MadcowD** [comment]
Lol, fuck good catch
