### ISSUE TITLE
Missing data version file

### ISSUE THREAD

**Issue by lbertge** [minerllabs/minerl#145]
After downloading the dataset, I'll run the following: 
```
> python3 -m minerl.viewer MineRLTreechop-v0 v1_absolute_grape_changeling-7_14600-16079

Traceback (most recent call last):
  File "/Users/albertge/anaconda3/lib/python3.7/site-packages/minerl/data/version.py", line 12, in assert_version
    assert os.path.exists(version_file), "more"
AssertionError: more
```

The source tells me that it's looking for a file called 'data/VERSION' (`data` here is the placeholder for the absolute directory). 

`$MINERL_DATA_ROOT` has been set to the correct data directory. And because the dataset folders have been changed, i.e. from `r2g1...` to `v1_...` I'm sure this is an issue, even after downloading the new dataset. 

FWIW, commenting out the line seems to work as advertised. I'm able to control the viewer without issue so far.

**Comment by MadcowD** [comment]
@brandonhoughton Are you sure you packaged the VERSION file in the  dataset?

**Comment by MadcowD** [comment]
@lbertge  How did you download the dataset?

**Comment by MadcowD** [comment]
@lbertge I just downloaded the data it looks like the VERSION file is in there. I'm pushing a fix that will only assert on the version file if its there, otherwise it will just check every prefix of all the files in the data directory.

**Comment by MadcowD** [comment]
@lbertge  Feel free to update to `minerl-0.2.2`  this should let you work in peace :) 
```
pip3 install --upgrade minerl
```

**Comment by lbertge** [comment]
Thanks. With the update, it works as intended now. Sorry about the trouble.
