### ISSUE TITLE
Disable env.render during competition

### ISSUE THREAD

**Issue by MadcowD** [minerllabs/minerl#159]
* we should disable env.render() in the docker container 
    - CMU can do this, we just need to know if their is an environment variable set that we can use to disable this.

**Comment by spMohanty** [comment]
We always have an env variable called as `AICROWD_IS_GRADING` set to True when the evaluation is in progress. 
So just checking for the presence of this env variable should do the trick.
cc. @skbly7

**Comment by MadcowD** [comment]
Is this on the submission container?
