### ISSUE TITLE
'Connection refused' to Instance port, causing hanging during env.reset()

### ISSUE THREAD

**Issue by albertwujj** [minerllabs/minerl#16]
In order to run on a headless server, I ran the given example code with 'xvfb-run python main.py', and got the below error:

![image](https://user-images.githubusercontent.com/21957230/59151042-7845d480-89e1-11e9-8328-f953606de8cf.png)

I am using Ubuntu 18.04

**Comment by MadcowD** [comment]
Do you see a Minecraft process start?

Could you send me you logs/minecraft_proc_9000 Logs?

**Comment by MadcowD** [comment]
Are you running with a monitor?

**Comment by albertwujj** [comment]
No monitor, running with displayless Paperspace machine, with xvfb-run as I mentioned.
My full script:
![image](https://user-images.githubusercontent.com/21957230/59159701-ed211900-8a8a-11e9-9ad8-81fcb0cfd463.png)
Adding logging did not result in any additional output.

Running the command seems to spawn one java process, stop executing that one, and then spawn a 2nd, continuing to execute the second. While hanging on env.reset() as described.
![image](https://user-images.githubusercontent.com/21957230/59159745-5f91f900-8a8b-11e9-89e0-f770c0cd51cb.png)

**Comment by MadcowD** [comment]
Ah, my bad. Could you try:
```
import logging
for handler in logging.root.handlers:
    logging.root.removeHandler(handler)
 logging.basicConfig(level=logging.DEBUG)
```

Also could you post your
```
./logs/minecraft_proc_9XXX.log
```

**Comment by MadcowD** [comment]
@albertwujj If you wanna talk on Discord I am on.

**Comment by MadcowD** [comment]
Feel free to also upgrade the package, I’ve changed the logging issues and the local host reference.

**Comment by albertwujj** [comment]
Hi Madcow,

I updated the package, and the script worked completely. Thanks!

**Comment by MadcowD** [comment]
Ah so strange! I bet your host blocked connections on 127.0.0.1!
