### ISSUE TITLE
"none"/"air" for equipped_items (observation)?

### ISSUE THREAD

**Issue by keisuke-nakata** [minerllabs/minerl#164]
`equipped_items` (which is part of observation) has options `'none', 'air'`.  
I am confused from the difference between among these options.

I can understand the "equip" `none, air` for *action* as [documented](http://minerl.io/docs/environments/handlers.html#tool-control-camera), but for observation, what do "equipped_items = none/air" mean?

**Comment by brandonhoughton** [comment]
`equip none` is a no-op action, it does not affect the state of the agent
`equip air` attempts to equip the item `air` which effectively unequips any item the agent is holding

Note that if the agent does not have any space in their inventory (and as such there are no free slots) `equip air` will not have any effect. This is a rare case however and we have not encountered this for agents in the competition.

**Comment by keisuke-nakata** [comment]
What is the difference between `observation.equipped_items.mainhand none` and `observation.equipped_items.mainhand air` ?

**Comment by MadcowD** [comment]
Well I suspect that if the user is equipping something not in the observation space it will be `none` and if there is nothing in the hand then it will be air. Perhaps we should make these one and the same.
