### ISSUE TITLE
What will happen if the agent would try to `place` items not present in the inventory?

### ISSUE THREAD

**Issue by keisuke-nakata** [minerllabs/minerl#165]
[Doc](http://minerl.io/docs/environments/handlers.html#tool-control-camera) says that "equip an item not present in the inventory" results in noop (= `equip none`), but is this same for `place`?

(And what will happen if the agent would try to `craft` an item which is impossible to craft with the items that the agent currently has?)

**Comment by brandonhoughton** [comment]
All handlers should no-op if the action is not possible. If you notice any behavior inconsistent with this pease raise it so we can address!
