### ISSUE TITLE
data.seq_iter() does not have 'batch_size' parameter

### ISSUE THREAD

**Issue by Mrugankakarte** [minerllabs/minerl#18]
Hi!

The `seq_iter()` function in data pipeline does not have `batch_size` as parameter as mentioned in [docs](http://www.minerl.io/docs/tutorials/data_sampling.html), according to your source files it is `max_sequence_len`. I request you to kindly make the changes in docs.

Thanks!
Mrugank Akarte

**Comment by lmc5190** [comment]
@brandonhoughton Documentation still reflects the incorrect parameter name here [http://minerl.io/docs/tutorials/data_sampling.html](http://minerl.io/docs/tutorials/data_sampling.html)

**Comment by brandonhoughton** [comment]
Fixed! Sorry for closing too early, just needed to publish the changes to the live documentation
