### ISSUE TITLE
Will do submitted scores refresh after MineRL updates?

### ISSUE THREAD

**Issue by keisuke-nakata** [minerllabs/minerl#188]
The submitted score depends on MineRL version because MineRL is still updated frequently and some of issues might be related to reward settings.
Will do the leaderboard scores refresh after MineRL version-up?

**Comment by MadcowD** [comment]
Yes, for any changes to the environments scores on the leaderboard sill be updated. On submission we verify that the minerl package you trained on is the correct version.
