### ISSUE TITLE
Hunger, health, and mobs

### ISSUE THREAD

**Issue by lbertge** [minerllabs/minerl#202]
Do we have any notion of hunger/health encoded in the state space? 

What kinds of mobs do we encounter in the environment?

**Comment by brandonhoughton** [comment]
There is no indication of health or hunger explicitly - agents can observe the camera shaking on receiving damage however. Mobs encountered are spawned by default Minecraft survival game rules for 1.12.2 - more info here: https://minecraft.gamepedia.com/Mob
