### ISSUE TITLE
data is not fine. Success metadata not working for dense environments.

### ISSUE THREAD

**Issue by Maxpridy** [minerllabs/minerl#203]
in MineRLObtainDiamond-v0
v1_cute_breadfruit_spirit-1_35476-37415
is {success:True} but not success data.

and...

![image](https://user-images.githubusercontent.com/16449397/62602263-51971200-b92e-11e9-9a98-8aa0cafac3db.png)
this is non-zero action_equip data(only success) but I don't understand what's going on.
Generally, I think 3, 5, and 7 are normal, like the last data.

Why is data like this? Is the action ignored or not saved properly?

**Comment by MadcowD** [comment]
Hi, what are the numbers you are outputting representing?

**Comment by MadcowD** [comment]
Nevermind, I understand. @BrandonHoughton is looking into it!

**Comment by brandonhoughton** [comment]
looks like he was successful at dying... 💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯
okay, looking into how this example actually got into the data.

We'll blacklist streams which are successful but don't actually get > 1024 reward in the next version of `minerl` and then make a perminantay fix in the data next release.

**Comment by MadcowD** [comment]
We are currently revalidating this. It appears that this works for the sparse environment (success is set to false) but not for the dense enviornment.

**Comment by MadcowD** [comment]
This has been fixed and will be released in MineRL 0.2.5
