### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by ThisIsIsaac** [minerllabs/minerl#212]
In [docs](http://minerl.io/docs/tutorials/first_agent.html#no-op-actions-and-a-better-policy)

There is a typo:

> we will only move forward, jump, attack, and changw the agent’s direction

> changw

should probably be 

> change

**Comment by MadcowD** [comment]
Hey would be awesome if you could make a PR for this!

**Comment by ThisIsIsaac** [comment]
Done!

https://github.com/minerllabs/minerl/pull/213
