### ISSUE TITLE
Done is never True in data iter for seq len 1

### ISSUE THREAD

**Issue by abiro** [minerllabs/minerl#217]
Hi,

I've found a bug in version `0.2.3` where the done flag is never set to True when requesting sequences of length 1. Code to reproduce:

```python
import minerl

data = minerl.data.make('MineRLObtainDiamond-v0', data_dir='./data')

# Iterate through a single epoch gathering sequences of at most 32 steps
# max_sequence_len has to be 0 to return sequences of length 1
diter = data.sarsd_iter(num_epochs=1, max_sequence_len=0,
                        include_metadata=True, seed=1)
i = 1
stream_name = None
for current_state, action, reward, next_state, done, meta in diter:
    if stream_name is None:
        stream_name = meta['stream_name']
        print(meta)
    if done[-1] or stream_name != meta['stream_name']:
        print(i, done)
        break
    i += 1

```

Prints:

```
{'success': True, 'duration_ms': 95250, 'duration_steps': 1905, 'total_reward': 19.0, 'stream_name': 'v1_cute_breadfruit_spirit-1_35476-37415'}
1906 [False]
```

The problem is the code only stops where the stream name changes on the 1906th step, but it should stop on the 1905th step, since the first demonstration has that many steps according to its meta data.

~I've addressed the `max_sequence_len` problem in [PR#216](https://github.com/minerllabs/minerl/pull/216).~

Thanks,
Agost

**Comment by abiro** [comment]
The cause of the problem seems to be that there is that the `done` arrays are always 1 longer than the other ones.

**Comment by abiro** [comment]
I've found an other issue which is probably related: when setting `max_sequence_len=32` (the default value), only 1848 observations are returned instead of 1905 for the first demonstration. Code to reproduce:

```python
import minerl

data = minerl.data.make('MineRLObtainDiamond-v0', data_dir='./data')

# Iterate through a single epoch gathering sequences of at most 32 steps
# max_sequence_len has to be 0 to return sequences of length 1
diter = data.sarsd_iter(num_epochs=1, max_sequence_len=0,
                        include_metadata=True, seed=1)
i = 1
stream_name = None
for current_state, action, reward, next_state, done, meta in diter:
    if stream_name is None:
        stream_name = meta['stream_name']
        print(meta)
    if done[-1] or stream_name != meta['stream_name']:
        print(i, done)
        break
    i += 1
```

Prints:
```
{'success': True, 'duration_ms': 95250, 'duration_steps': 1905, 'total_reward': 19.0, 'stream_name': 'v1_cute_breadfruit_spirit-1_35476-37415'}
1848
```

**Comment by MadcowD** [comment]
Hi, taking a look at this now! Thanks for all of the debug information :) I'll get back to you with a detailed explaination soon!

**Comment by MadcowD** [comment]
@abiro  It looks like your first sample doesn't necessarily iterate  to the end of the first stream when I try and reproduce (maybe my number of workers is higher). I will post a snippet which reproduces the error.
