### ISSUE TITLE
Seeding not supported in MineRLTreechop-v0 environment

### ISSUE THREAD

**Issue by fortuin** [minerllabs/minerl#220]
It seems that the `env.seed()` function does not have any effect in the MineRLTreechop-v0 environment. It always seems to start in the exact same location in the same environment. Is that on purpose? I noticed that the demonstrations for the Treechop task in the MineRL data set do seem to start at different locations...

**Comment by brandonhoughton** [comment]
Currently this is a known bug, see issue #154 

We are working on fixing it - it has to do with the map used for `MineRLTreechop-v0` where only the forest biome is generated which is handled by a pre-defined map.

**Comment by kaixin96** [comment]
@brandonhoughton Have you fixed it? The deadline of the 1st round is approaching ! !

**Comment by MadcowD** [comment]
@kaixin96 We're planning on moving the deadline up.

**Comment by kaixin96** [comment]
@MadcowD Do I understand correctly that you are planning on moving the deadline nearer ?
