### ISSUE TITLE
Strange evaluation scores on submission results

### ISSUE THREAD

**Issue by keisuke-nakata** [minerllabs/minerl#221]
I submitted the template repository starter kit and I found some strange results:
- The maximum steps pre episode seems `18004`
- Sometimes the template agent obtains score of 10.000 or 14.000 or 18.000 or 30.000, which seems impossible with the fixed action agent on ObtainDiamond task.

**Comment by MadcowD** [comment]
This is a major issue and should be completed in the next release of MineRL (0.2.5)

**Comment by MadcowD** [comment]
Fixed!
