### ISSUE TITLE
CompassAngle changing even when agent does not move (in MineRLNavigateDense)

### ISSUE THREAD

**Issue by manuelsh** [minerllabs/minerl#228]
In the MineRLNavigateDense-v0 environment, even if one doesn’t perform any action, the compassAngle keeps changing.

Minimal example:

```
import minerl
import gym
env = gym.make('MineRLNavigateDense-v0')
obs = env.reset()
env_act= {'attack':0, 
               'jump':0, 
               'forward':0, 
               'back':0, 
               'left':0, 
               'right':0, 
               'sprint':0, 
               'sneak':0, 
               'camera':[0,  0]}
next_obs, rew, done, info = env.step(env_act)
print('compassAngle:',obs['compassAngle'])
print('next compassAngle:', next_obs['compassAngle'])
```
will return two different values for `compassAngle` even after the camera not being moved.

**Comment by brandonhoughton** [comment]
This is actually a feature of how Minecraft handles the compass observations rather than a bug. The compass in Minecraft has momentum and starts at a fixed position so there can be some oscillation

**Comment by manuelsh** [comment]
Thanks for clarifying. Maybe it would be good to add it to the documentation, couldn't find that there.
