### ISSUE TITLE
How do I get the seed used for each recording in the dataset?

### ISSUE THREAD

**Issue by Sohojoe** [minerllabs/minerl#229]
I am looking to implement Inverse Reinforcement Learning by having the environment use the same seed as the recording and step through to the step number I want to train from.
\

**Comment by brandonhoughton** [comment]
Unfortunately, seeding is a relatively new feature for MineRL - as such it was not implemented on the data collection server. 

It is possible to achieve the same world state using the file world loader, and introducing new teleportation logic into the malmo commands for loading worlds from file, however mob spawning mechanics, random events, and other elements fixed using seeding would not be accounted for.

**Comment by Sohojoe** [comment]
thanks - I could give it a try and see if it deviates. can you give me some hints on how to do the file world loader and teleport? I'm new to MineRL
