### ISSUE TITLE
Equipping wooden-pickaxe problem

### ISSUE THREAD

**Issue by kimbring2** [minerllabs/minerl#230]
I am trying to equip a wooden-pickaxe item when it is in my inventory by using a action['equip'] = 3 in MineRLObtainDiamond environment. But I can not equip. 

I can not find a solution about that problem.

Please help me.

**Comment by vihangp** [comment]
I am also facing a similar issue. 

@kimbring2 did you manage to resolve it?

Please help.

**Comment by kimbring2** [comment]
@vihangp No, I can not solve it. I will tell you if I solve it!!

**Comment by kimbring2** [comment]
@vihangp 

Hi, I solve the problem. Try use a 'wooden_pickaxe' instead of 3 and an 'action = env.action_space.noop()' at first line!
``
if (wooden_pickaxe >= 1):
    action = env.action_space.noop()
    action['place'] = 0; action['craft'] = 0; 
    action['nearbyCraft'] = 0; action['nearbySmelt'] = 0
    action['attack'] = 0; action['camera'][0] = 0; action['camera'][1] = 0;
    action['forward'] = 0; action['jump'] = 0;
    action['equip'] = 'wooden_pickaxe'
    wooden_flag = wooden_flag + 1
``

**Comment by vihangp** [comment]
@kimbring2 Thanks man :)

**Comment by vihangp** [comment]
@kimbring2 This is not working for me. We tried exactly what you did, but we are still not able to do this. 

Did you try it multiple times?

**Comment by kimbring2** [comment]
@vihango Yes, I first test it by using a https://github.com/minerllabs/minerl/blob/master/tests/local/handler_test.py. When I changed equip item name as Wooden_Pickaxe, It worked well. And then I implemented it into my own code three times, confirmed it worked well. I think it is best way add a line 'action['equip'] = 'wooden_pickaxe'' without any state condition restrict. If you have a item in your inventory, agent will immediately equip it. And you can see it observation.

**Comment by marioyc** [comment]
Hi @brandonhoughton , is this `<EquipCommands/>` tag necessary? It seems to be missing in obtainDiamond, obtainDiamondDense, obtainIron and obtainIronDense.

Also `<PlaceCommands/>` seems to be missing in the navigation tasks.

**Comment by kimbring2** [comment]
@marioyc I also removed out-commented line in obtainDiamond.xml and added a <Item type="minecraft:wooden_pickaxe"/>' line. But, nothing was happened with realted with wooden_pickaxe. I assume that out-commenting and adding a new line do not effect to environment.

`
<EquipCommands/>
            
            
            
`

**Comment by brandonhoughton** [comment]
This has been added in #264

**Comment by brandonhoughton** [comment]
Merged in minerl 0.2.5
