### ISSUE TITLE
Observation returned by env.step() changes key from 'inventory' to 'dirt' near navigate goal

### ISSUE THREAD

**Issue by albert-yue** [minerllabs/minerl#24]
I was following along the tutorial in the docs and making some of my own edits to the base code and found that in the two time steps right before done changes to True, the 'inventory' key is replaced with a 'dirt' key, with the value also becoming an `OrderedDict`. The structure of the returned observation looks fine otherwise.

On a tangent, could you add bullet pointing for the documentation of `env.step()`? Currently it's one block of text and looks incomplete.

**Comment by nicomon24** [comment]
Adding on this, in the navigate environments, the 'compassAngle' changes from float to a numpy array!

**Comment by MadcowD** [comment]
I believe this is fixed with `minerl` > 0.1.10. Please upgrade to see if this fixes your issue
```
pip3 install --upgrade minerl
```

**Comment by nicomon24** [comment]
Everything seems fine now, thanks!
