### ISSUE TITLE
How to solve HTTPRange issue encountered when using minerl.data.download?

### ISSUE THREAD

**Issue by 00yk** [minerllabs/minerl#266]
Hi there. I was hoping to get the environment running.
Followed the installation guide, brew cask installed the jdk8.
Also checked that jdk8 is the default version of my operating system.
However, when trying to download the dataset, I encountered this issue below.

`>>> import minerl`
`>>> minerl.data.download(directory='dataset/')`
`Server does not support HTTPRange. threads_count is set to 1.
URL error encountered when downloading - please try again
None`

Searching through the issues, I didn't find similar problems. Has anyone ever encountered this issue or am I just forget to do something necessary?

Thanks for any advice about what I need to do.

**Comment by minerllabs** [comment]
This was an issue with the data server going down briefly that day.
The error thrown by our PySmartDL dependency is misleading, HTTPRange is supported but the real issue was that the data server was offline.

It is online now!

**Comment by zyyhhxx** [comment]
It seems the server is offline again.

**Comment by MadcowD** [comment]
Hey just wanted to update you all, were working on this!

Sorry again!

**Comment by callmemars** [comment]
Any updates on this?

**Comment by jdecid** [comment]
Still having the same problems since ~2 days ago. Is this because the server is down or for any other reason?

**Comment by edward1997104** [comment]
Could I know if there are updates on this? It seems that the data still cannot be downloaded. Thank you very much!

**Comment by KarolisRam** [comment]
I downloaded the data about a week ago without problems, but it's not working now. I used the direct link:
[https://router.sneakywines.me/minerl-v1/data_texture_0_low_res.tar.gz](https://router.sneakywines.me/minerl-v1/data_texture_0_low_res.tar.gz)

**Comment by jfpettit** [comment]
I'm also unable to download the data, but haven't tried the direct link.

**Comment by edward1997104** [comment]
It seems the direct link is not working as well. Will there be other links for datasets?

**Comment by rlalpha** [comment]
Probably it is because of the version problem
You can try
```shell_script
pip install -U minerl
# if not work, can try below one
pip install minerl==0.3.1
# if not work again
wget https://minerl-asia.s3.amazonaws.com/v3/data_texture_0_low_res.tar
```

**Comment by brandonhoughton** [comment]
Just a note for those who stumble on this thread - direct links to download MineRL datasets are not supported and subject to move. If you would like to find the direct links see the [download](https://github.com/minerllabs/minerl/blob/master/minerl/data/download.py) code for the most up-to-date mirrors.
