### ISSUE TITLE
Unexpected array size in Treechop-v0 Dataset

### ISSUE THREAD

**Issue by Mrugankakarte** [minerllabs/minerl#28]
Hi!

Is the data pre-processed or we have to handle different input image sizes? While going through `Treechop-v0` Dataset, encountered this error.

![minerl_test](https://user-images.githubusercontent.com/12859725/59177583-297f7280-8b7a-11e9-83e9-059f7f989782.PNG)

**Comment by MadcowD** [comment]
Looking into this. Most likely the higher resolution version of the dataset snuck into the dataset that we published.

**Comment by Mrugankakarte** [comment]
Any simple solution to resize the array to 64x64x3?

**Comment by MadcowD** [comment]
Check if the shape is wrong and then just throw the sample out!

**Comment by brandonhoughton** [comment]
We can filter the data while loading so this won't be seen when using the api. Unfortunately fixing this the right way will require re-downloading the data. Thank you for finding this!

**Comment by Mrugankakarte** [comment]
Yup..I am doing what @MadcowD said...checking shape and if it's not 64x64x3, skipping to next sample.

**Comment by Mrugankakarte** [comment]
Apparently it's not only in `Treechop-v0`...I found it in `NavigateExtremeDense-v0` as well. Thought I would let you know.

**Comment by MadcowD** [comment]
@brandonhoughton

**Comment by minerllabs** [comment]
Thanks for posing this issue - those samples will be re-rendered and published in the next distribution of the data

**Comment by SaminYeasar** [comment]
Hi, I sampled 100 batch with sequence length 1 on MineRLNavigate env got 74 with dim (64,64,3). So there must a good amount of data out of shape. Please let us know when the updated datasets are ready for download.

**Comment by MadcowD** [comment]
@SaminYeasar Currently rerendering the data now! Sorry about this :S

**Comment by brandonhoughton** [comment]
Fixed with data version r2g1
