### ISSUE TITLE
Dataset Unavailable Error "URL error encountered when downloading - please try again"

### ISSUE THREAD

**Issue by MrBubsters** [minerllabs/minerl#284]
This issue was closed in #266 however the problem seems to have come back. 
Error occurs when trying to download dataset using minerl.data.download()

**Comment by brandonhoughton** [comment]
As of time of writing I am able to download the dataset - can you confirm you are still experiencing this issue? The server was down for maintenance recently, however it should be working now

**Comment by MrBubsters** [comment]
Issue has been resolved. minerl no longer throws http error when downloading. Must have just been during the maintenance that it wasn't working.

**Comment by rohanhpatel** [comment]
Hi, I am using the MineRL dataset for a project, and I receiving a similar error. What should I do?

**Comment by MadcowD** [comment]
Hy all we're working on this! Sorry again.
