### ISSUE TITLE
How to get the size of the action_space

### ISSUE THREAD

**Issue by yashiro32** [minerllabs/minerl#289]
print(env.action_space.shape)
TypeError: 'NoneType' object is not callable

print(env.action_space.keys())
AttributeError: 'Dict' object has no attribute 'keys'

print(env.action_space.values())
AttributeError: 'Dict' object has no attribute 'values'

**Comment by MadcowD** [comment]
This follows the gym Dict action space: See https://github.com/openai/gym/blob/master/gym/spaces/dict.py

**Comment by k-sashank** [comment]
Were you able to retrieve the size of action_space using this?
