### ISSUE TITLE
Observation is up-side-down

### ISSUE THREAD

**Issue by keisuke-nakata** [minerllabs/minerl#29]
The returned observation `pov` is up-side-down.

![image (3)](https://user-images.githubusercontent.com/6150143/59188480-b6deb900-8bb2-11e9-85fe-d47339c5ecc8.png)

(left: `plt.imshow('foo.png', env.reset()['pov'])`,
right: Minecraft window on my laptop)

**Comment by MadcowD** [comment]
@keisuke-nakata  Good find! This is fixed now.

Please upgrade you package
```
pip3 install --upgrade minerl
```
