### ISSUE TITLE
Where are the scripts for baselines?

### ISSUE THREAD

**Issue by yashiro32** [minerllabs/minerl#290]
https://github.com/minerllabs/minerl/blob/master/tests/excluded/treechop_dqn_test.py

```
from baselines import logger
from baselines import deepq
from baselines.deepq.replay_buffer import ReplayBuffer
from baselines.common.schedules import LinearSchedule
```

**Comment by TheDevMinerTV** [comment]
bump

**Comment by MadcowD** [comment]
Ah this is openAI baselines, not sure which version it's pegged to.

You should check out http://github.com/minerllabs/baselines
