### ISSUE TITLE
Dataset is not available. Mirrors are down.

### ISSUE THREAD

**Issue by DanGSun** [minerllabs/minerl#291]
Code I'm running:
 ```python
import minerl
minerl.data.download('dataset')
```
Error:
 ```
Server does not support HTTPRange. threads_count is set to 1.
URL error encountered when downloading - please try again.
None
```

**Comment by kool601** [comment]
Having same issue, hope it's solved soon.

**Comment by NotNANtoN** [comment]
Same here... I also tried all the mirror links in this forum, none seem to work.

**Comment by DanGSun** [comment]
@MadcowD, are you still supporting this project?

**Comment by kool601** [comment]
@NotNANtoN I see you opened a new issue, #292 
Does this mean you got the dataset to download? If so, please elaborate, I'm still having this issue with downloading the dataset.

**Comment by NotNANtoN** [comment]
@kool601 No I did not manage to download it, I think all the links are down.

I did find a version of the dataset I previously downloaded on my server. So I spend some time trying to figure out how I can share it via BitTorrent. I created a torrent file and used the transmission-daemon to seed it, but unfortunately, I am unable to download it to my laptop via this method. If you have any feedback or ideas on how to make it work (ports are open, I checked) let me know. Here is the magnet link, maybe someone has an idea:

magnet:?xt=urn:btih:b37b88b9cfaf0ed0c371da7d53c22c284c35c089&dn=minerl%5Fdataset.zip&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969

**Comment by DanGSun** [comment]
> @kool601 No I did not manage to download it, I think all the links are down.
> 
> I did find a version of the dataset I previously downloaded on my server. So I spend some time trying to figure out how I can share it via BitTorrent. I created a torrent file and used the transmission-daemon to seed it, but unfortunately, I am unable to download it to my laptop via this method. If you have any feedback or ideas on how to make it work (ports are open, I checked) let me know. Here is the magnet link, maybe someone has an idea:
> 
> ```
> magnet:?xt=urn:btih:b37b88b9cfaf0ed0c371da7d53c22c284c35c089&dn=minerl%5Fdataset.zip&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969
> ```

I've tried, the link is not working. If you want, you can upload it here: http://academictorrents.com/.
They host Datasets.

**Comment by MadcowD** [comment]
We are working on it!

**Comment by DanGSun** [comment]
@MadcowD, can you share it on torrents? I've seen, that this is not first time that happened.

**Comment by DanGSun** [comment]
And can you also share your dataset collecting software? If sb will want to make their own dataset.

**Comment by NotNANtoN** [comment]
Good to know that you are still here! @MadcowD 

Btw, I added the torrent to academictorrents, but I did not see an option to actually upload the full dataset:
https://academictorrents.com/details/b37b88b9cfaf0ed0c371da7d53c22c284c35c089

**Comment by kool601** [comment]
I think it's working, it just needs to take the torrent and upload it to a mirror to seed it. So for now it can't be downloaded. Hopefully once it's being seeded it'll work.

**Comment by kool601** [comment]
Hey, it appears to be back up! Let's hope it stays this way.
![Screenshot_1](https://user-images.githubusercontent.com/13336171/74094962-948d9a00-4ab7-11ea-9e5a-03b248de4683.png)

**Comment by MadcowD** [comment]
Sorry friends!
