### ISSUE TITLE
Best way to sample random images

### ISSUE THREAD

**Issue by fedetask** [minerllabs/minerl#294]
Is there a more efficient way to sample completely random images than doing this?

```python
generators  = [] # add to this list generators for all datasets created by data.make()

while True:
    generator = random.sample(generators, 1)[0]
    for s, _, _, _, _ in generator.sarsd_iter(num_epochs=1, max_sequence_len=1, queue_size=1):
        img = s['pov'][0] # This is the randomly sampled image
        break
```

**Comment by MadcowD** [comment]
I reccomend taking the dataset and writing out all of the POV frames as `png`s. The fundamental issue here is that the data is stored in mp4's, so if you wanted to do this randomly online you'd need to load the MP4's and then scan to a random position then discard the MP4.
