### ISSUE TITLE
[new_pipeline_with_render] env.env_spec.unwap_action modifies action in-place

### ISSUE THREAD

**Issue by keisuke-nakata** [minerllabs/minerl#312]
Is this an intended behavior?
(I could not find the exact line which did this :bow: )

```python
env = gym.make('MineRLTreechopVectorObf-v0')
obs = env.reset()
action = env.action_space.sample()
o, r, d, i = env.step(action)

print(action)
print(env.env_spec.unwap_action(action))
print(action)  # action modified in-place
print(env.env_spec.unwap_action(action))  # AssertionError
```

**Comment by Miffyli** [comment]
I think the function in question is defined [here](https://github.com/minerllabs/minerl/blob/new_pipeline_with_render/minerl/herobraine/wrappers/obfuscation_wrapper.py#L121). Looks like it is intended, but if this is regarding the competition I do not think obtaining un-unobfuscated actions is allowed ^^.

**Comment by brandonhoughton** [comment]
We added a deep-copy to the wrapping! Should be fixed now
