### ISSUE TITLE
KeyError "attack" on obfuscated env.step

### ISSUE THREAD

**Issue by Miffyli** [minerllabs/minerl#314]
Running dummy code like the following results to `KeyError: "attack"`:

```python
import minerl, gym
env = gym.make("MineRLObtainDiamondVectorObf-v0")
obs = env.reset()
_ = env.step(env.action_space.noop()) # Also happens if you try to feed in {'vector': np.random.random((64,))}
```

The error occurs at following line, just recently changed by commit 6bf8f2c6

https://github.com/minerllabs/minerl/blob/a04654c3555354c722237b15254dbd0b005c2698/minerl/env/core.py#L423

System/Versions:
* Ubuntu 16.04
* MineRL 0.3.0 (PyPi)
* Python 3.6

**Comment by brandonhoughton** [comment]
should be  `elif isinstance(bottom_env_spec.action_space.spaces[act], gym.spaces.Discrete):`
