### ISSUE TITLE
Provide option for downloading a subset of the data by experiment

### ISSUE THREAD

**Issue by minerllabs** [minerllabs/minerl#33]
Currently the data is packaged as a single tar file. Move to multiple tar files, one per experiment and add the ability to filter these in minerl.data.download()

**Comment by brandonhoughton** [comment]
Tentative support via manual download links here:
https://router.sneakywines.me/minerl/MineRLNavigateDense-v0.tar
https://router.sneakywines.me/minerl/MineRLNavigateExtremeDense-v0.tar
https://router.sneakywines.me/minerl/MineRLNavigateExtreme-v0.tar
https://router.sneakywines.me/minerl/MineRLNavigate-v0.tar
https://router.sneakywines.me/minerl/MineRLObtainDiamondDense-v0.tar
https://router.sneakywines.me/minerl/MineRLObtainDiamond-v0.tar
https://router.sneakywines.me/minerl/MineRLObtainIronPickaxe-v0.tar
https://router.sneakywines.me/minerl/MineRLObtainIronPickaxeDense-v0.tar
https://router.sneakywines.me/minerl/MineRLTreechop-v0.tar
