### ISSUE TITLE
Shape of action changes when MineRLTreechopVectorObf-v0 step is executed

### ISSUE THREAD

**Issue by liquidnode** [minerllabs/minerl#343]
After executing step of the MineRLTreechopVectorObf-v0 environment, the shape of action['vector'] changes from (64,) to (1,64). I don't think this is an intended behavior. I haven't checked if this also happens in the other Vector environments, but this could possibly be an universal problem.

**Comment by MadcowD** [comment]
Oooh good catch, could you write a script to reproduce it?

**Comment by liquidnode** [comment]
I tried to replicate the problem in a minimal example:

```import gym
import minerl

env = gym.make("MineRLTreechopVectorObf-v0")

env.reset()
action = env.action_space.sample()
action_shape = action['vector'].shape
env.step(action)
assert len(action_shape) == len(action['vector'].shape)```

Everything works as expected. I noticed that it was actually a problem of a gym wrapper I forgot about. I'm sorry for reporting this bug here.

**Comment by MadcowD** [comment]
Thanks so much for following up and using the package!
