### ISSUE TITLE
Possibilities to replay collected trajectories in the gaming environment

### ISSUE THREAD

**Issue by elicassion** [minerllabs/minerl#348]
Hi MineRL Team,

Are there any possibilities that I can replay the dataset in the game environment rather than simply visualizing the pixels?

Thanks!

**Comment by MadcowD** [comment]
We are working on open-sourcing our recorder at the moment!

**Comment by elicassion** [comment]
> We are working on open-sourcing our recorder at the moment!

Sounds great! Thanks for your efforts!
