### ISSUE TITLE
Provide sample metadata when retreving samples from the environmet

### ISSUE THREAD

**Issue by minerllabs** [minerllabs/minerl#40]
When using
`data = minerl.data.make('MineRLObtainDiamond-v0')`
`data.seq_iter()`

one only has access to `obs, rew, done, act`, but no information about from which demonstration this particular sample actually belongs. Add handler to provide information on which sample, duration, and if the sample was successful or not

**Comment by kaixin96** [comment]
Metadata is helpful when one wants to filter the data (e.g. only loading the successful demonstrations).
