### ISSUE TITLE
window is too small to observe training (Add env.render()) functionality!

### ISSUE THREAD

**Issue by Sohojoe** [minerllabs/minerl#43]
Hi, I am following the getting started guide and its impossible to see what the agent is doing because the window is so small:

<img width="1440" alt="Screen Shot 2019-06-11 at 11 41 37 PM" src="https://user-images.githubusercontent.com/4400544/59329112-f2f14700-8ca2-11e9-879f-3937180f384c.png">

I am not able to stretch the window (as I can with Atari). 

My device is a MacBook Pro 15" 2016

**Comment by MadcowD** [comment]
You can use the pixels returned by the observation to render frames in python itself using Pygame or matplotlib.

I will make sure that we had first class support for this later with env.render()!

**Comment by MadcowD** [comment]
You can use the pixels returned by the observation to render frames in python itself using Pygame or matplotlib.

I will make sure that we had first class support for this later with env.render()!

**Comment by Sohojoe** [comment]
@MadcowD I created a wrapper that does this based on the gym code

``` python
import gym
import numpy as np
from gym.envs.classic_control import rendering


class RenderObservations(gym.Wrapper):
    def __init__(self, env, display_vector_obs=True):
        gym.Wrapper.__init__(self, env)
        self.viewer = None
        
    def step(self, action):
        ob, reward, done, info = self.env.step(action)
        self._visual_obs = ob["pov"].copy()
        return ob, reward, done, info

    def _renderObs(self, obs):
        if self.viewer is None:
            self.viewer = rendering.SimpleImageViewer()
        self.viewer.imshow(obs)
        return self.viewer.isopen

    def render(self, mode='human', **kwargs):
        if mode == 'human':
            self._renderObs(self._visual_obs)
        return self._visual_obs

    def reset(self):
        return self.env.reset()

    def close(self):
        self.env.close()
        if self.viewer is not None:
            self.viewer.close()
            self.viewer = None

```

**Comment by Mrugankakarte** [comment]
Do you use it like this?
```
env = gym.make('NavigateDense-v0')
env = RenderObservations(env)

obs, _ = env.reset()
done = False
net_reward = 0

while not done:
    env.render()
    action = env.action_space.noop()

    action['camera'] = [0, 0.03*obs["compassAngle"]]
    action['back'] = 0
    action['forward'] = 1
    action['jump'] = 1
    action['attack'] = 1

    obs, reward, done, info = env.step(
        action)

    net_reward += reward
    print("Total reward: ", net_reward)
```

Sorry never used wrappers before!

**Comment by Sohojoe** [comment]
I call the render after the step - I made a slight change to make sure it copies the observations on reset

**Comment by MadcowD** [comment]
@Sohojoe  This is now integrated into minerl, please update your package! **No need to use the wrapper now :) **
```
pip3 install --upgrade minerl
```
