### ISSUE TITLE
Dataset 2019-06-10 Obtain Diamond issues

### ISSUE THREAD

**Issue by Crissman** [minerllabs/minerl#44]
Please see the Gist: https://gist.github.com/Crissman/727f9500e1795eac88197e7628e68ce8

Reward function is not working correctly.  Of 115 trajectories, only 5 show non-zero reward, and those rewards are not consistent with the published evaluation function. For example, a successful diamond find should have a reward of 1+2+4+4…+256+1024 = 1571, which none of five scoring trajectories have.
Over 40 trajectories are under five minutes in length.
Some of the trajectories are using admin commands, for example,`MineRLObtainDaimond-v0\player_stream_bogus_guava_djinn-17_31716-33336`  They stay in the lobby, and create a diamond, pick it up --profit!
Many of the trajectories start with the "lobby" screen, but then go on to do apparent normal actions. They have the same name as some sessions ending in the lobby, such as `bogus-guava-djinn` above. Are they using admin actions?

Please run the above linked Gist on the next data set, to check before publishing.

Thanks,

**Comment by brandonhoughton** [comment]
Fixed in r2g1
