### ISSUE TITLE
How to get older versions of minerl datasets

### ISSUE THREAD

**Issue by vivandoshi08** [minerllabs/minerl#441]
Hello, I would like to download the v1 and v2 datasets , but it seems like you can only get v3 datasets. Is there any other way to get v1 and v2 datasets

**Comment by brandonhoughton** [comment]
Why would you want the old versions? They have some bugs and are missing observations added in the latest version

**Comment by vivandoshi08** [comment]
I had built different code using datasets v1 and v2, but I lost the datasets, so I was wondering if I can get the old datasets to run my code again.

**Comment by brandonhoughton** [comment]
I found v2: https://s3.console.aws.amazon.com/s3/object/minerl?region=us-east-1&prefix=v2/data_texture_0_low_res.tar.gz
I'm not sure where v1 went

**Comment by vivandoshi08** [comment]
When I click the link, it says access denied, and I can't download the data. What do I do?

**Comment by shwang** [comment]
Hi @vivandoshi08 , Brandon sent you an AWS console link. You can find the (public) download link here: https://minerl.s3.amazonaws.com/v2/data_texture_0_low_res.tar.gz

Closing the issue for now because this should resolve the problem, and it's been a while.
