### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by Mar1noc** [minerllabs/minerl#444]
`This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.`
`
#################################################`
`
         ForgeGradle 2.2-SNAPSHOT-3966cea        `
`
  https://github.com/MinecraftForge/ForgeGradle  `
`
#################################################`

               Powered by MCP unknown               

             http://modcoderpack.com             

         by: Searge, ProfMobius, Fesh0r,         

         R4wk, ZeuX, IngisKahn, bspkrs           

`#################################################`
`
Found AccessTransformer: malmomod_at.cfg`
`
:deobfCompileDummyTask`
`
:deobfProvidedDummyTask
`
`:getVersionJson`
`
:extractUserdev
`
`FAILURE: Build failed with an exception.`
`
* What went wrong:
Could not resolve all dependencies for configuration ':forgeGradleUserDevPackage'.
> Could not resolve net.minecraftforge:forge:1.11.2-13.20.0.2228.
  Required by:
      com.microsoft.MalmoMod:Minecraft:0.37.0
   > Could not resolve net.minecraftforge:forge:1.11.2-13.20.0.2228.
    > Could not get resource 'https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2228/forge-1.11.2-13.20.0.2228.pom'.
         > Could not GET 'https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2228/forge-1.11.2-13.20.0.2228.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 28.914 secs

Minecraft process finished unexpectedly. There was an error with `Malmo.`

How fix that?

**Comment by OrdinaryHacker101** [comment]
Can anybody please explain what is going on? I am having the exact same error.

**Comment by kimbring2** [comment]
Me too

**Comment by OrdinaryHacker101** [comment]
@kimbring2 , @Mar1noc I've fixed the problem using this solution: https://github.com/minerllabs/minerl/issues/450

**Comment by kimbring2** [comment]
@OrdinaryHacker101 Oh, I can solve the issue by method of your link. Thank you very much. I can continue my research

**Comment by OrdinaryHacker101** [comment]
You are most welcome @kimbring2

**Comment by aesthetic0001** [comment]
I know this is a dumb question, but how can you build minerl from src?

**Comment by OrdinaryHacker101** [comment]
@aesthetic0001 I have no clue at all ngl LOL.

**Comment by aesthetic0001** [comment]
fixed using py 3.7.9

**Comment by brandonhoughton** [comment]
Closing as issue seems to be resolved
