### ISSUE TITLE
RuntimeWarning Raised when downloading dataset.

### ISSUE THREAD

**Issue by ForrestZeng1** [minerllabs/minerl#469]
I was trying to download the dataset to my directory using the command:
`python3 -m minerl.data.download`

However, this returns an error. 
`/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py:126: RuntimeWarning: 'minerl.data.download' found in sys.modules after import of package 'minerl.data', but prior to execution of 'minerl.data.download'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))`

What can I do to fix this? I have tried this on another computer, and it returns the same error. I believe it may be a Mac-specific issue, and thus I am looking for solutions to this.

**Comment by Miffyli** [comment]
That part of the code has probably broken during changes. Try using the functions [shown in step 3 here](https://minerl.io/docs/tutorials/index.html#installation). That should do the trick.

**Comment by ForrestZeng1** [comment]
I did so, however, it returns this:

```requests.exceptions.ConnectionError: HTTPSConnectionPool(host='router.sneakywines.me', port=443): Max retries exceeded with url: /minerl/data_texture_0_low_res.md5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15e22c760>: Failed to establish a new connection: [Errno 61] Connection refused'))```

I tried visiting the site "router.sneakywines.me," however, it states that the site cannot be reached. Is this a problem with the server?

**Comment by Miffyli** [comment]
Hmm I am not quite sure why it is pointing you to such addresses. You can download the data manually the following address: https://minerl.s3.amazonaws.com/v3/data_texture_0_low_res.tar

**Comment by ForrestZeng1** [comment]
Thanks! Is there a way of downloading only one experiment dataset? I want to test only one of the environments, and 60 gb is a bit much for my computer.

**Comment by KarolisRam** [comment]
Links to all of the separate datasets:

https://minerl-europe.s3.amazonaws.com/v3/MineRLNavigate-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLNavigateVectorObf-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLNavigateDense-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLNavigateDenseVectorObf-v0.tar

https://minerl-europe.s3.amazonaws.com/v3/MineRLNavigateExtreme-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLNavigateExtremeVectorObf-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLNavigateExtremeDense-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLNavigateExtremeDenseVectorObf-v0.tar

https://minerl-europe.s3.amazonaws.com/v3/MineRLObtainDiamond-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLObtainDiamondVectorObf-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLObtainDiamondDense-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLObtainDiamondDenseVectorObf-v0.tar

https://minerl-europe.s3.amazonaws.com/v3/MineRLObtainIronPickaxe-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLObtainIronPickaxeVectorObf-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLObtainIronPickaxeDense-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLObtainIronPickaxeDenseVectorObf-v0.tar

https://minerl-europe.s3.amazonaws.com/v3/MineRLTreechop-v0.tar
https://minerl-europe.s3.amazonaws.com/v3/MineRLTreechopVectorObf-v0.tar

https://minerl-europe.s3.amazonaws.com/v3/MineRLObtainDiamondSurvivalVectorObf-v0.tar

**Comment by nicolaefilat** [comment]
@KarolisRam all the links are dead now

**Comment by rotem154154** [comment]
https://www.kaggle.com/datasets/ryanrudes/minerl

**Comment by dami2106** [comment]
Has there been any update on reviving the dataset? Currently Im not able to use MineRL 0.4.4 to get access to the data, and all above links are dead...

**Comment by suvelmuttreja** [comment]
@KarolisRam @Miffyli do you have the updated links for downloading? These links are still dead and the python code doesn't work either

**Comment by KarolisRam** [comment]
does this help?
[https://zenodo.org/records/11996496](https://zenodo.org/records/11996496)
