### ISSUE TITLE
MineRL pip installation.

### ISSUE THREAD

**Issue by ForrestZeng1** [minerllabs/minerl#472]
Upon doing `pip3 install minerl=0.3.6`

I receive this error:

`ERROR: Could not find a version that satisfies the requirement matplotlib==3.0.3 (from minerl)
ERROR: No matching distribution found for matplotlib==3.0.3`

I tried installing matplotlib using `pip3 install matplotlib==3.0.3`, but it also returned a similar error.

Is this an error with the requirements? How can I fix this?

**Comment by Miffyli** [comment]
You may install any version of matplotlib, i.e. `pip3 install matplotlib`. This package is not crucial for running MineRL, apart from the data visualizer. You can install MineRL installing the dependencies from `requirements.txt`, apart from `matplotlib`, and then install MineRL with `pip3 install --no-deps minerl==0.3.6`
