### ISSUE TITLE
Could not GET 'http://repo.spongepowered.org/maven/org/spongepowered/mixin/0.7.5-SNAPSHOT/maven-metadata.xml'. Received status code 520 from server: Origin Error

### ISSUE THREAD

**Issue by ForrestZeng1** [minerllabs/minerl#474]
Upon running a mineRL program, the process dies with this error. I was able to fix this by editing `build.gradle` directly in my minerl package directory by changing `http://repo.spongepowered.org/maven/org/spongepowered/mixin/0.7.5-SNAPSHOT/maven-metadata.xml` to `https://repo.spongepowered.org/maven/org/spongepowered/mixin/0.7.5-SNAPSHOT/maven-metadata.xml`. However, I noticed that the version on this github seemed to be fixed, with the correct URL. 

Do I have a different mineRL version? I installed it with `pip3 install minerl==0.3.6`.

I did `pip3 show minerl`, and it returned this.
```
Name: minerl
Version: 0.3.6
Summary: MineRL environment and data loader for reinforcement learning from human demonstration in Minecraft
Home-page: http://github.com/minerllabs/minerl
Author: MineRL Labs
Author-email: minerl@andrew.cmu.edu
License: MIT
Location: /Users/forrestzeng/Library/Python/3.8/lib/python/site-packages
Requires: opencv-python, matplotlib, setuptools, requests, Pyro4, lxml, dill, numpy, tqdm, typing, getch, psutil, coloredlogs, gym, ipython
```
It all seems correct, but I don't see why it isn't matching with the Github version. Is this a general issue with the versions not matching? If so, would it cause any problems?

**Comment by Miffyli** [comment]
MineRL on pypi (the service that hosts `pip install ...` packages) is old one and has not been updated with the fix. The current version here on `dev` is 0.4, which contains that fix along some other modifications.

On Linux you can install this repository with `pip install git+https://github.com/minerllabs/minerl`, but on Windows it seems to be throwing some odd errors (at least on my machine)
