### ISSUE TITLE
installation error: Gradle can't download 'com.github.johnrengelman.shadow'

### ISSUE THREAD

**Issue by ianchen28** [minerllabs/minerl#554]
trying to install using 'pip install minerl'

OS:
Linux and Windows10 both

jdk : 
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

got the errorlog:
    Welcome to Gradle 4.10.2!
    
    Here are the highlights of this release:
     - Incremental Java compilation by default
     - Periodic Gradle caches cleanup
     - Gradle Kotlin DSL 1.0-RC6
     - Nested included builds
     - SNAPSHOT plugin versions in the `plugins {}` block
    
    For more details see https://docs.gradle.org/4.10.2/release-notes.html
    
    Starting a Gradle Daemon (subsequent builds will be faster)
    
    FAILURE: Build failed with an exception.
    
    * Where:
    Build file '/tmp/pip-install-3xcw0qsn/minerl/build/lib/minerl/Malmo/Minecraft/build.gradle' line: 31
    
    * What went wrong:
    Plugin [id: 'com.github.johnrengelman.shadow', version: '1.2.4'] was not found in any of the following sources:
    
    - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
    - Plugin Repositories (could not resolve plugin artifact 'com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:1.2.4')
      Searched in the following repositories:
        Gradle Central Plugin Repository
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 6s

**Comment by ianchen28** [comment]
Linux


openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by KarolisRam** [comment]
Could you try the same procedure again? I also had similar gradle errors a couple days ago on both Ubuntu and Colab and now it works fine.

**Comment by ianchen28** [comment]
> Could you try the same procedure again? I also had similar gradle errors a couple days ago on both Ubuntu and Colab and now it works fine.

It works for me!
I reinstalled jdk 8 and run `pip install minerl --no-cache-dir` and everything went well. (win10, Ubuntu and macos)
Thank you and wierd enough _(:з」∠)_
