### ISSUE TITLE
env = gym.make('MineRLNavigateDense-v0') ERROR

### ISSUE THREAD

**Issue by Sparks123** [minerllabs/minerl#555]
when I run this command. An error happened（TypeError: can't pickle _thread.RLock objects
）
 I don't know how to fix it. Please Help

**Comment by Sparks123** [comment]
maybe it is due to my  minerl version which is 0.4.0?

**Comment by Miffyli** [comment]
Hey! Can you provide full code you try to run? 
Meanwhile see if this helps you: https://minerl.readthedocs.io/en/latest/notes/windows.html

**Comment by shwang** [comment]
Hi @Sparks123 -- this is a known error with MineRL v0.4.0 and Python 3.6, fixed by https://github.com/minerllabs/minerl/pull/550.

**Comment by shwang** [comment]
This should be automatically fixed in our next (upcoming) release, MineRL v0.4.1, but in the meantime you can do oone of the following:

(1) Upgrade to Python 3.7 or higher
(2) Manually apply the patch in #550 
(3) Install MineRL from source by downloading the repo and running `pip install -e .`

**Comment by shwang** [comment]
I'm closing this issue for now because it will be resolved by the next release.

**Comment by Sparks123** [comment]
> This should be automatically fixed in our next (upcoming) release, MineRL v0.4.1, but in the meantime you can do oone of the following:
> 
> (1) Upgrade to Python 3.7 or higher
> (2) Manually apply the patch in #550
> (3) Install MineRL from source by downloading the repo and running `pip install -e .`

It works. Thanks a lot.
