### ISSUE TITLE
Cannot upgrade/install the newest Minerl package

### ISSUE THREAD

**Issue by Smu-Tan** [minerllabs/minerl#558]
I installed Minerl 0.3.6 version,  but failed to upgrade it.

Here's the error I encountered:

![image](https://user-images.githubusercontent.com/79228128/125466362-b5db90ec-3680-4c5b-af27-5848eebcfc3b.png)

**Comment by Miffyli** [comment]
Hmm this might be some remnant files that do not wish to be deleted. I think your best bet is to either manually remove the directory in question and then call `pip install minerl`, or to create a fresh environment.

**Comment by Smu-Tan** [comment]
> Hmm this might be some remnant files that do not wish to be deleted. I think your best bet is to either manually remove the directory in question and then call `pip install minerl`, or to create a fresh environment.

Thx for help! I tried to delete files that were mentioned in the errors then install minerl, as well as create a new environment. Unfortunately, both methods cannot work.

**Comment by Miffyli** [comment]
Hmm quick googling seems to indicate this might be a OS issue (e.g. anti-virus locking files) https://github.com/pypa/pip/issues/4734

Does the package install correctly for you? This seems to be some temp cleaning up issues. You can try this by opening Python and doing `import minerl`. Some people suggest running the pip command as admin (not really super safe, but that is just how Windows wants do things...).

**Comment by SammyTaleb** [comment]
I have exactly the same issue, I cannot install the minerl package. A quick view to the traceback error shows that the building fails because the folder directory cannot be found : "[Win Error 3]"

![image](https://user-images.githubusercontent.com/70745808/125469878-2c196054-35b7-4adc-9116-2a68fd884448.png)

**Comment by Smu-Tan** [comment]
> I have exactly the same issue, I cannot install the minerl package. A quick view to the traceback error shows that the building fails because the folder directory cannot be found : "[Win Error 3]"
> 
> ![image](https://user-images.githubusercontent.com/70745808/125469878-2c196054-35b7-4adc-9116-2a68fd884448.png)

Can you try pip install minerl==0.3.6? that's how I installed the package before, but I cant upgrade it to 0.4.0.

**Comment by Miffyli** [comment]
For the time being you can try using `pip install minerl==0.3.7`. This version has most of the utilities of 0.4.0, except for the new BASALT environments and a new dataloader, but you can still get started with it :)

Meanwhile could you guys provide the environments and operating systems you use so I could try replicating this issue (e.g. are you using anaconda? Windows 10/11? etc)

**Comment by Smu-Tan** [comment]
> For the time being you can try using `pip install minerl==0.3.7`. This version has most of the utilities of 0.4.0, except for the new BASALT environments and a new dataloader, but you can still get started with it :)
> 
> Meanwhile could you guys provide the environments and operating systems you use so I could try replicating this issue (e.g. are you using anaconda? Windows 10/11? etc)

Hi, 0.3.7 works for me! I'm using windows 10 (version 2004), conda 4.9.2.

**Comment by SammyTaleb** [comment]
@Smu-Tan I've tried the version 0.3.6 but no distribution is found for matplotlib==3.0.3

@Miffyli minerl==0.3.7 failed building wheel but curiously it works.

I am using anaconda on Windows 10 20H2
The environment is a fresh one, with only tensorflow, numpy and their dependencies installed on it
Do you need other details ?

**Comment by Miffyli** [comment]
Thanks @Smu-Tan and @SammyTaleb ! This should be enough, I will look into this in the following days :)

**Comment by Miffyli** [comment]
Hmm I was not able to reproduce the error on my machine :/. Steps:
1. Install miniconda (Python 3.8) from here: https://docs.conda.io/en/latest/miniconda.html
2. Create new environment in the miniconda prompt and install minerl:
```
conda create -n minerl python=3.9
conda activate minerl
pip install minerl
```
3. In python prompt run
```
import minerl, gym
env = gym.make("MineRLTreechop-v0")
obs = env.reset()
```

Other things you might want to check out:
- Check that you have long-paths enabled in Windows: https://lifehacker.com/windows-10-allows-file-names-longer-than-260-characters-1785201032
- Try the above "run pip with admin" in case your anti-virus is in the way

**Comment by Sparks123** [comment]
I have exactly the same issue. Have you guys solve it?

**Comment by Sparks123** [comment]
> I have exactly the same issue. Have you guys solve it?

my os is windows 10. But minerl(0.4.0) can be installed on Ubuntu

**Comment by Miffyli** [comment]
If anybody can share a _full_ output log when you try to install/run MineRL, that would go a long way! Meanwhile, also check your java versions that they match (see here https://github.com/minerllabs/minerl/issues/559#issuecomment-879248534 )

**Comment by Sparks123** [comment]
> Hmm I was not able to reproduce the error on my machine :/. Steps:
> 
> 1. Install miniconda (Python 3.8) from here: https://docs.conda.io/en/latest/miniconda.html
> 2. Create new environment in the miniconda prompt and install minerl:
> 
> ```
> conda create -n minerl python=3.9
> conda activate minerl
> pip install minerl
> ```
> 
> 1. In python prompt run
> 
> ```
> import minerl, gym
> env = gym.make("MineRLTreechop-v0")
> obs = env.reset()
> ```
> 
> Other things you might want to check out:
> 
> * Check that you have long-paths enabled in Windows: https://lifehacker.com/windows-10-allows-file-names-longer-than-260-characters-1785201032
> * Try the above "run pip with admin" in case your anti-virus is in the way

I finally solve the problem with doing nothing but try several times with your solutions(run pip with admin and Check that you have long-paths enabled in Windows). Anyway thanks a lot.
