### ISSUE TITLE
Installation error on windows 10

### ISSUE THREAD

**Issue by piaomiaohuanchen** [minerllabs/minerl#563]
error: [WinError 3] System can not find the route 。: 'C:\\Users\\username\\AppData\\Local\\Temp\\pip-installmhtjrmew\\minerl_d58bcd107d554d29af2a7e6e4f71e315\\build\\lib\\minerl\\Malmo\\Minecraft\\run\\gradle\\caches\\4.10.2\\scripts\\crcb8k40lahbsikr1x3znkmr1\\cp_proj\\cp_proj70b1361a260e0ceb212a59c45f680ebd\\cp_proj70b1361a260e0ceb212a59c45f680ebd.lock'

**Comment by Miffyli** [comment]
Sounds like you might be running in the limited path length on Windows. Can you try if following this guide helps? https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by piaomiaohuanchen** [comment]
Hello, through the method you gave you, I solved the problem I encountered, thank you.
At the same time, I found that directly installing mine==0.3.7 can also solve this problem.

**Comment by conarchllc** [comment]
Addressing limited path length on Windows 10 fixed the problem with installing 0.4.0. Thanks!
