### ISSUE TITLE
Bug in data_pipeline

### ISSUE THREAD

**Issue by sheng-han-zhang** [minerllabs/minerl#572]
Hi,
    There is a bug in current version(0.4.0) minerl about include_metadata. The following is a link to the position of bug.

    https://github.com/minerllabs/minerl/blob/dev/minerl/data/data_pipeline.py#L129

    If we want to get infor like success, we need to enable include_metadata. But in current version, this is controled by include include_monitor_data, which I think is a typo.

Regards,
Shenghan

**Comment by Miffyli** [comment]
Nice catch! We would be happy to accept a PR that fixes this (I need to dash myself right now, so I do not have time to properly test the change) :)
