### ISSUE TITLE
pypi release minerl 0.4.1 has metadata version 0.4.1a2 

### ISSUE THREAD

**Issue by juliusfrost** [minerllabs/minerl#584]
In the release commit for tag `v0.4.1`, the version number isn't changed from the preview version number `0.4.1a1`:
https://github.com/minerllabs/minerl/blob/34089efaf80d2f68e0866d40b52d9d76221f30a0/setup.py#L171

It seems this is also not the same as the pypi version `0.4.1` which has `0.4.1a2` as the version number. This breaks pip installs for packages that depend on minerl 0.4.1.

**Comment by Miffyli** [comment]
Thanks for pointing this out! 
Poking @shwang if he can look into this and update pypi version if necessary.

**Comment by shwang** [comment]
Oops, thanks for catching this! I'm abroad right now and I don't have easy access to a dev environment to test `minerl` installs. Could you take a look at this issue @brandonhoughton?

**Comment by JiangPeng-666** [comment]
I also encountered this problem, and an error happened when  building wheel for minerl  (setup.py) ..
I've tried three laptops and changed the version for Python many times, but it still did not work.

**Comment by brandonhoughton** [comment]
Great catch - I will bump the version later today

**Comment by brandonhoughton** [comment]
Should be fixed with version 0.4.2, unfortunately I'm not able to upload another 0.4.1 version to pypi

**Comment by shwang** [comment]
Thanks!
