### ISSUE TITLE
`env.reset()` does not completely reset the env

### ISSUE THREAD

**Issue by keisuke-nakata** [minerllabs/minerl#59]
`env.reset()` does not reset the blocks broken by agents.

This movie is the first evaluation episode from my script.
[openaigym.video.0.224.video000000.mp4.zip](https://github.com/minerllabs/minerl/files/3300102/openaigym.video.0.224.video000000.mp4.zip)

And here is the movie after some episodes are finished.
[openaigym.video.0.224.video000016.mp4.zip](https://github.com/minerllabs/minerl/files/3300110/openaigym.video.0.224.video000016.mp4.zip)

You can see the scenery of the first frame of these movies are same, but the ground condition is completely different.
The latter movie shows there is a huge hole around the agent and it is stuck during chopping tree.

Is it possible to completely "reset" the game?

**Comment by TimZF** [comment]
i think this should fix it
https://github.com/minerllabs/minerl/pull/61/commits/fb26e14ed3323b5fd5b1f6bc2f0b03c6318203be
