### ISSUE TITLE
Minimized after starting and returns error

### ISSUE THREAD

**Issue by ElectricTurtle32** [minerllabs/minerl#601]
When I launch it, the minecraft window shows up, loads. and then resacles to a very small size and I can't resize it.
Current code:
"""
import minerl
import gym
env = gym.make('MineRLNavigateDense-v0')

obs = env.reset()

done = False
while not done:
    action = env.action_space.sample() 
 
    # One can also take a no_op action with
    # action =env.action_space.noop()
    
 
    obs, reward, done, info = env.step(
        action)
"""
error: 
"""
Failed to delete the temporary minecraft directory.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python39\lib\site-packages\minerl\env\malmo.py", line 614, in <lambda>
    atexit.register(lambda: self._destruct())
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python39\lib\site-packages\minerl\env\malmo.py", line 771, in _destruct
    minerl.utils.process_watcher.reap_process_and_children(self.minecraft_process)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python39\lib\site-packages\minerl\utils\process_watcher.py", line 76, in reap_process_and_children
    procs = process.children(recursive=True)[::-1] + [process]
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\__init__.py", line 271, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=9564)
"""

**Comment by Miffyli** [comment]
Hey. This is expected behaviour. The small window is required to run MineRL (to render the image), but this is sent to the Python code. Use opencv/cv2 library in Python to visualize the image (or alternatively, install older MineRL `pip install minerl==0.3.7` which still shows the image in the small window).

Please close the issue if you have no further questions :)

**Comment by ElectricTurtle32** [comment]
I forgot to mention, Afterword it closes restuning the error specified

**Comment by Miffyli** [comment]
Yup that is expected: the environment is closed correctly (but throws an error on Windows). You can ignore the warning/error as long as the Minecraft instance disappears :)

**Comment by ElectricTurtle32** [comment]
Ok so I can do like tree choping?

**Comment by Miffyli** [comment]
Moved discussion to Discord.
