### ISSUE TITLE
First Time Lunching Minerl Error 

### ISSUE THREAD

**Issue by Xhram** [minerllabs/minerl#626]
Here is the console out put of it [https://pastebin.com/DvYUHVEw](https://pastebin.com/DvYUHVEw)
I have no clue how to fix this I am on windows 11 btw

**Comment by Miffyli** [comment]
Hey. Double-check your Java version; MineRL specifically requires JDK 8. You seem to be running something newer (JDK 17?). On Windows, the most robust way to fix this is to remove all other installations of Java and then install JDK 8 specifically.

**Comment by Xhram** [comment]
I Solved it I had to remove a bit of paths form Sytem variables
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Program Files\Common Files\Oracle\Java\javapath
C:\ProgramData\Oracle\Java\javapath
And also set one to
C:\Program Files\Java\jdk1.8.0_311\bin

**Comment by Xhram** [comment]
also I hade JDK 8 installed but it was not set to use JDK 8

**Comment by Miffyli** [comment]
Ok, closing as solved :)
