### ISSUE TITLE
Version 0.4.4: AttributeError: 'socket' object has no attribute 'client_socket_send_message'

### ISSUE THREAD

**Issue by miguel-arrf** [minerllabs/minerl#632]
Hi!:)

After creating a custom enviroment, from [here](https://minerl.readthedocs.io/en/latest/tutorials/custom_environments.html), and using this main:

```
import gym
from mlg_wb_specs import MLGWB

def main():
    abs_MLG = MLGWB()
    abs_MLG.register()
    env = gym.make("MLGWB-v0")

    env.make_interactive(port=6666, realtime=True)
    obs = env.reset()

    done = False
    while not done:
        env.render()
        action = env.action_space.noop()
        obs, reward, done, info = env.step(action)

```

After executing it, a black Minecraft window appears (the screen is black and only the inventory GUI appears).

How should I now open the interactive view? If I open a new terminal where I execute `python3 -m minerl.interactor 6666
`, this error message appears: "AttributeError: 'socket' object has no attribute 'client_socket_send_message'", from `/minerl/env/_multiagent.py", line 792, in _TO_MOVE_hello
`.

Thank you so much!

**Comment by Miffyli** [comment]
Hey. Try installing MineRL from github with `pip3 install git+https://github.com/minerllabs/minerl`. This issue was fixed in a recent patch, but not reflected in the pypi version :)

**Comment by miguel-arrf** [comment]
Thank's for the quick reply. I've just updated. It is now working! 🤩
