### ISSUE TITLE
Bugs while running MineRL on Mac

### ISSUE THREAD

**Issue by nhsjdiwlcnsv** [minerllabs/minerl#634]
Hi, I'm trying to run my first MineRL bot using the basic example from MineRL website on **MacOS Monterey 12.4** (https://minerl.readthedocs.io/en/latest/tutorials/first_agent.html), but MineRL behaves absolutely unexpectedly.

**MineRL and Java info:**
<img width="1440" alt="Снимок экрана 2022-06-20 в 14 28 55" src="https://user-images.githubusercontent.com/46066382/174592346-dd56654c-9289-4409-9481-0d8fb1739816.png">

**The script I'm trying to run:**
```
import minerl
import logging
import gym


def main():
    env = gym.make('MineRLNavigateDense-v0')
    obs = env.reset()
    done = False
    net_reward = 0

    while not done:
        action = env.action_space.noop()

        action['camera'] = [0, 0.03 * obs["compass"]["angle"]]
        action['back'] = 0
        action['forward'] = 1
        action['jump'] = 1
        action['attack'] = 1

        obs, reward, done, info = env.step(action)

        net_reward += reward
        print(obs)

    print("Total reward: ", net_reward)


if __name__ == '__main__':
    main()

```
I use the ```python3 [path-to-file]/main.py``` command to run my script. After I run my script I see the Minecraft 1.11.2 window opening and loading Minecraft. After that, when I see the main Minecraft menu, the environment automatically loads and I can see the world. 

However, after a second this window closes, and another window (much smaller one, which actually must open  according to the MineRL docs), opens. The problem here is that I do not see anything except for the last second of my script execution. I can only guess what happens by looking at the logs in the console due to ```print(obs)``` line in my script.

**Here's what I get:**

```
...
...
...
...
        [ 90, 117,  55]]], dtype=uint8), 'compass': {'angle': array(-76.13989)}, 'inventory': {'dirt': array(0)}}
{'pov': array([[[144, 184, 255],
        [144, 183, 255],
        [144, 183, 255],
        ...,
        [143, 183, 255],
        [144, 183, 255],
        [144, 183, 255]],

       [[145, 184, 255],
        [144, 184, 255],
        [144, 183, 255],
        ...,
        [144, 183, 255],
        [144, 183, 255],
        [144, 183, 255]],

       [[145, 184, 255],
        [145, 184, 255],
        [145, 184, 255],
        ...,
        [144, 184, 255],
        [144, 184, 255],
        [145, 184, 255]],

       ...,

       [[ 76,  99,  47],
        [ 76,  99,  47],
        [ 88, 115,  54],
        ...,
        [ 93, 121,  57],
        [ 67,  87,  41],
        [ 67,  87,  41]],

       [[ 84, 110,  52],
        [ 87, 114,  54],
        [ 88, 114,  54],
        ...,
        [ 87, 114,  54],
        [ 67,  87,  41],
        [ 67,  87,  41]],

       [[ 92, 121,  57],
        [ 88, 115,  54],
        [ 86, 113,  53],
        ...,
        [ 76,  99,  47],
        [ 90, 117,  55],
        [ 67,  87,  41]]], dtype=uint8), 'compass': {'angle': array(-76.065735)}, 'inventory': {'dirt': array(0)}}
{'pov': array([[[144, 183, 255],
        [144, 183, 255],
        [144, 183, 255],
        ...,
        [144, 183, 255],
        [144, 183, 255],
        [144, 184, 255]],

       [[145, 184, 255],
        [144, 184, 255],
        [144, 183, 255],
        ...,
        [144, 184, 255],
        [144, 184, 255],
        [145, 184, 255]],

       [[145, 184, 255],
        [145, 184, 255],
        [144, 184, 255],
        ...,
        [145, 184, 255],
        [145, 184, 255],
        [145, 184, 255]],

       ...,

       [[ 86, 112,  53],
        [ 92, 120,  56],
        [ 83, 109,  51],
        ...,
        [ 88, 115,  54],
        [ 85, 111,  52],
        [ 78, 102,  48]],

       [[ 84, 109,  51],
        [ 82, 107,  50],
        [ 74,  97,  45],
        ...,
        [ 82, 107,  50],
        [ 83, 109,  51],
        [ 77, 101,  47]],

       [[ 73,  95,  44],
        [ 67,  87,  41],
        [104, 135,  64],
        ...,
        [ 75,  98,  46],
        [ 82, 107,  50],
        [ 79, 103,  49]]], dtype=uint8), 'compass': {'angle': array(-75.989044)}, 'inventory': {'dirt': array(0)}}
{'pov': array([[[144, 183, 255],
        [144, 183, 255],
        [144, 183, 255],
        ...,
        [144, 184, 255],
        [144, 184, 255],
        [145, 184, 255]],

       [[145, 184, 255],
        [144, 183, 255],
        [144, 183, 255],
        ...,
        [145, 184, 255],
        [145, 184, 255],
        [145, 184, 255]],

       [[145, 184, 255],
        [145, 184, 255],
        [144, 184, 255],
        ...,
        [145, 184, 255],
        [145, 184, 255],
        [145, 184, 255]],

       ...,

       [[ 67,  87,  41],
        [ 82, 106,  50],
        [ 82, 106,  50],
        ...,
        [ 99, 129,  61],
        [ 79, 103,  48],
        [ 79, 103,  48]],

       [[ 82, 106,  50],
        [ 82, 106,  50],
        [ 83, 108,  51],
        ...,
        [ 84, 110,  52],
        [ 85, 111,  52],
        [ 99, 130,  61]],

       [[ 83, 108,  51],
        [ 83, 108,  51],
        [ 85, 111,  52],
        ...,
        [ 80, 104,  49],
        [ 85, 111,  52],
        [ 95, 124,  58]]], dtype=uint8), 'compass': {'angle': array(-75.91965)}, 'inventory': {'dirt': array(0)}}
Total reward:  65.59717224538326
```

As you see, the bot is changing his compass angle at the very least, so I assume that the script itself works correctly. The only problem is that I can't see anything. Moreover, after my program is executed, the small window of my bot's pov appears to be working and shows me **this** (I have resized it somehow...):

<img width="858" alt="Снимок экрана 2022-06-19 в 13 50 30" src="https://user-images.githubusercontent.com/46066382/174588015-0d43aa72-20f0-4bd7-88d9-e4f01e7e84c5.png">

I also want to mention that I thought the bugs were caused by running my script without ```xvfb-run```, but as I understood from reading several issues here and questions on StackOverflow, there is no ```xvfb``` on Mac, but ```XQuartz``` can be used as alternative, however even running the bot with XQuartz installed and working in background I encountered the same bugs.

What can be the source of my issue and how can it be fixed?

**Comment by Miffyli** [comment]
Hey. This is expected behaviour and in fact docs are out of date: in v0.4.x, a small window should appear but remain the same over the execution of the script (e.g., white or one image stuck). Sometimes wonky stuff happens like this where after closing the script the window remains or begins to update. Unfortunately we did not test MineRL extensively on Mac and do not have bandwidth to develop it. However it sounds like the script does work for you (with just derp behaviour) :)

**Comment by nhsjdiwlcnsv** [comment]
Thank you for help! :)

**Comment by mishashkarubski** [comment]
Oh, I have another question: since that small window remains static over the whole time my bot is working, how can I track the bots performance besides looking at logs in the command line? I mean, is there any way to watch the whole process in Minecraft?

**Comment by mishashkarubski** [comment]
Update: after I have installed ```pyglet``` via ```pip3 install pyglet``` I started to get this window after my script is executed:
<img width="1092" alt="Снимок экрана 2022-06-21 в 14 07 48" src="https://user-images.githubusercontent.com/46066382/174785893-341c43ce-c105-4df9-81e5-3179f09f2a99.png">

As I see in the docs, it should be visible the whole time while the code is running, but I only see this window when the small static window is closed and console states that mission ended.
