### ISSUE TITLE
[v1.0.0] Installation meet with gradle error on Windows 11

### ISSUE THREAD

**Issue by xieleo5** [minerllabs/minerl#636]
I tried to install the new mineRL on my windows computer, but I meet with several error.
First is that, `setup_output = subprocess.check_output(['bash.exe', 'setup_mcp.sh']).decode()` cannot launch the correct git bash in my computer. It will launch `bash.exe` under `C:\Windows\System32` and then it cannot find the git command. It will throw error like this:
```
Collecting git+https://github.com/minerllabs/minerl@v1.0.0
  Cloning https://github.com/minerllabs/minerl (to revision v1.0.0) to c:\users\16388\appdata\local\temp\pip-req-build-en_h3rmi
  Running command git clone -q https://github.com/minerllabs/minerl 'C:\Users\16388\AppData\Local\Temp\pip-req-build-en_h3rmi'
  Running command git checkout -b v1.0.0 --track origin/v1.0.0
  branch 'v1.0.0' set up to track 'origin/v1.0.0'.
  Switched to a new branch 'v1.0.0'
  Resolved https://github.com/minerllabs/minerl to commit aeb7c1b1a0cc8614ed8bd57e94c4614d1d04a12e
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\16388\anaconda3\envs\minerl\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\16388\\AppData\\Local\\Temp\\pip-req-build-en_h3rmi\\setup.py'"'"'; __file__='"'"'C:\\Users\\16388\\AppData\\Local\\Temp\\pip-req-build-en_h3rmi\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\16388\AppData\Local\Temp\pip-pip-egg-info-x3asqyd0'
         cwd: C:\Users\16388\AppData\Local\Temp\pip-req-build-en_h3rmi\
    Complete output (24 lines):
    setup_mcp.sh: line 6: git: command not found
    setup_mcp.sh: line 7: cd: MCP-Reborn: No such file or directory
    setup_mcp.sh: line 8: git: command not found
    setup_mcp.sh: line 10: ./gradlew: No such file or directory
    patch_mcp.sh: line 5: cd: /mnt/host/c/Users/16388/AppData/Local/Temp/pip-req-build-en_h3rmi/scripts/../minerl/MCP-Reborn: No such file or directory
    patch: unrecognized option: s
    BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

    Usage: patch [OPTIONS] [ORIGFILE [PATCHFILE]]

        -p N    Strip N leading components from file names
        -i DIFF Read DIFF instead of stdin
        -R      Reverse patch
        -N      Ignore already applied patches
        -E      Remove output files if they become empty
        --dry-run       Don't actually change files
    cp: can't create directory './src/main/resources': No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\16388\AppData\Local\Temp\pip-req-build-en_h3rmi\setup.py", line 203, in <module>
        prep_mcp()
      File "C:\Users\16388\AppData\Local\Temp\pip-req-build-en_h3rmi\setup.py", line 184, in prep_mcp
        os.chdir(workdir)
    FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\16388\\AppData\\Local\\Temp\\pip-req-build-en_h3rmi\\minerl\\MCP-Reborn'
    ----------------------------------------
WARNING: Discarding git+https://github.com/minerllabs/minerl@v1.0.0. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
So I just change `'bash.exe'` to the `git_bash_path = pathlib.WindowsPath(r"C:\Program Files\Git\bin\bash.exe")` where my local git bash was installed. And it can safely pass the bash scripts.

After that, when I run `pip install .` I'll receive such error:
```  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\16388\anaconda3\envs\minerl\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\16388\\AppData\\Local\\Temp\\pip-req-build-5f4rmkgw\\setup.py'"'"'; __file__='"'"'C:\\Users\\16388\\AppData\\Local\\Temp\\pip-req-build-5f4rmkgw\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\16388\AppData\Local\Temp\pip-pip-egg-info-jsdh7kbj'
         cwd: C:\Users\16388\AppData\Local\Temp\pip-req-build-5f4rmkgw\
    Complete output (56 lines):
    Cloning into 'MCP-Reborn'...
    Note: switching to '1.16.5-20210115'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by switching back to a branch.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -c with the switch command. Example:

      git switch -c <new-branch-name>

    Or undo this operation with:

      git switch -

    Turn off this advice by setting config variable advice.detachedHead to false

    HEAD is now at 1e71be5 Update README.md
    patch: unrecognized option: s
    BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

    Usage: patch [OPTIONS] [ORIGFILE [PATCHFILE]]

        -p N    Strip N leading components from file names
        -i DIFF Read DIFF instead of stdin
        -R      Reverse patch
        -N      Ignore already applied patches
        -E      Remove output files if they become empty
        --dry-run       Don't actually change files
    > Task :downloadMCMeta
    > Task :downloadAssets

    BUILD SUCCESSFUL in 8s
    2 actionable tasks: 2 executed

    FAILURE: Build failed with an exception.

    * What went wrong:
    Task 'shadowJar' not found in root project 'mcp-reborn'.

    * Try:
    Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 4s
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\16388\AppData\Local\Temp\pip-req-build-5f4rmkgw\setup.py", line 205, in <module>
        prep_mcp()
      File "C:\Users\16388\AppData\Local\Temp\pip-req-build-5f4rmkgw\setup.py", line 200, in prep_mcp
        subprocess.check_call('{} clean build shadowJar'.format(gradlew).split(' '), cwd=workdir)
      File "C:\Users\16388\anaconda3\envs\minerl\lib\subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['gradlew.bat', 'clean', 'build', 'shadowJar']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding file:///C:/Users/16388/Desktop/minerl. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It seems that task `shadowJar` is not found by the gradle. Can anyone help me about this? I really have no idea.

**Comment by xieleo5** [comment]
I found the reason, I installed gradle on my computer before, and `gradle.bat` automatically choose to use the gradle on my computer. And the version of gradle is incorrect. After I remove gradle from my PATH, it can be installed correctly.

**Comment by Miffyli** [comment]
👍  Thanks for reporting this and finding the fix! I am not super familiar with gradle, but definitely if one is installed in global paths, it would mess up the installation process. Now I know how to help others out with similar issues :).

Closing as resolved.

**Comment by fajrulfx** [comment]
> So I just change `'bash.exe'` to the `git_bash_path = pathlib.WindowsPath(r"C:\Program Files\Git\bin\bash.exe")`

Hi @xieleo5, can you specify where this change should be made?  I've changed `bash.exe` in setup.py lines 136 and 154, but I still get error of bash.exe. Thank you.

**Comment by Miffyli** [comment]
@fajrulfx Clone the repository and replace all occurances of `bash.exe` with full path to the `bash.exe` in your machine, and then do `pip install .` inside that repository.

**Comment by fajrulfx** [comment]
Thank you for the fast response. The `bash.exe` thing finally works, but then I get an error regarding `gradlew.bat` like above. However, in this case, I don't have Gradle installation in my PATH. Here's the error log:

``
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\fajrul\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Fajrul\\AppData\\Local\\Temp\\pip-req-build-jv4gf0hu\\setup.py'"'"'; __file__='"'"'C:\\Users\\Fajrul\\AppData\\Local\\Temp\\pip-req-build-jv4gf0hu\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Fajrul\AppData\Local\Temp\pip-pip-egg-info-5uoxqh4t'
         cwd: C:\Users\Fajrul\AppData\Local\Temp\pip-req-build-jv4gf0hu\
    Complete output (134 lines):
    Cloning into 'MCP-Reborn'...
    Note: switching to '1.16.5-20210115'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by switching back to a branch.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -c with the switch command. Example:

      git switch -c <new-branch-name>

    Or undo this operation with:

      git switch -

    Turn off this advice by setting config variable advice.detachedHead to false

    HEAD is now at 1e71be5 Update README.md

    > Configure project :
    [MixinGradle] Skipping eclipse integration, extension not found
    * * * * * * * * * * * * * * * * * * * * * * * *
    These are the repositories after plugins have been applied:
     | - MavenRepo -> https://repo.maven.apache.org/maven2/
     | - BintrayJCenter -> https://jcenter.bintray.com/
     | - maven -> https://repo.spongepowered.org/maven/
     | - maven2 -> https://maven.minecraftforge.net/
     | - BUNDELED_1780058540 -> downloads to: /C:/Users/Fajrul/.gradle/caches/forge_gradle/bundeled_repo/
     | - maven3 -> https://libraries.minecraft.net/
    * * * * * * * * * * * * * * * * * * * * * * * *
    Repositories after removing proxied repos:
     | - MavenRepo -> https://repo.maven.apache.org/maven2/
     | - BintrayJCenter -> https://jcenter.bintray.com/
     | - maven -> https://repo.spongepowered.org/maven/
     | - maven2 -> https://maven.minecraftforge.net/
     | - BUNDELED_1780058540 -> downloads to: /C:/Users/Fajrul/.gradle/caches/forge_gradle/bundeled_repo/
     | - maven3 -> https://libraries.minecraft.net/
    * * * * * * * * * * * * * * * * * * * * * * * *

    > Task :verifyRepos
    Checking BuildScript Repositories:
     | - [ OK ]: MavenLocal -> file:/C:/Users/Fajrul/.m2/repository/
     | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
     | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
     | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
    Checking Project Repositories:
     | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
     | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
     | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
     | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
     | - [ OK ]: BUNDELED_1780058540 (accepted custom MC repo)
     | - [FAIL]: maven3 -> https://libraries.minecraft.net/

    > Task :downloadMCMeta
    > Task :downloadAssets

    Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
    Use '--warning-mode all' to show the individual deprecation warnings.
    See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

    BUILD SUCCESSFUL in 10s
    3 actionable tasks: 3 executed

    > Configure project :
    [MixinGradle] Skipping eclipse integration, extension not found
    * * * * * * * * * * * * * * * * * * * * * * * *
    These are the repositories after plugins have been applied:
     | - MavenRepo -> https://repo.maven.apache.org/maven2/
     | - BintrayJCenter -> https://jcenter.bintray.com/
     | - maven -> https://repo.spongepowered.org/maven/
     | - maven2 -> https://maven.minecraftforge.net/
     | - BUNDELED_275951191 -> downloads to: /C:/Users/Fajrul/.gradle/caches/forge_gradle/bundeled_repo/
     | - maven3 -> https://libraries.minecraft.net/
    * * * * * * * * * * * * * * * * * * * * * * * *
    Repositories after removing proxied repos:
     | - MavenRepo -> https://repo.maven.apache.org/maven2/
     | - BintrayJCenter -> https://jcenter.bintray.com/
     | - maven -> https://repo.spongepowered.org/maven/
     | - maven2 -> https://maven.minecraftforge.net/
     | - BUNDELED_275951191 -> downloads to: /C:/Users/Fajrul/.gradle/caches/forge_gradle/bundeled_repo/
     | - maven3 -> https://libraries.minecraft.net/
    * * * * * * * * * * * * * * * * * * * * * * * *

    > Task :verifyRepos
    Checking BuildScript Repositories:
     | - [ OK ]: MavenLocal -> file:/C:/Users/Fajrul/.m2/repository/
     | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
     | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
     | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
    Checking Project Repositories:
     | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
     | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
     | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
     | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
     | - [ OK ]: BUNDELED_275951191 (accepted custom MC repo)
     | - [FAIL]: maven3 -> https://libraries.minecraft.net/

    > Task :clean
    > Task :downloadMappings
    > Task :mcp:downloadConfig
    > Task :extractSrg
    > Task :createMcp2Srg
    > Task :deleteSchemas
    > Task :copySchemas
    > Task :jaxb
    > Task :compileJava FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileJava'.
    > Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_311 contains a valid JDK installation.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
    Use '--warning-mode all' to show the individual deprecation warnings.
    See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

    BUILD FAILED in 10s
    10 actionable tasks: 10 executed
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Fajrul\AppData\Local\Temp\pip-req-build-jv4gf0hu\setup.py", line 203, in <module>
        prep_mcp()
      File "C:\Users\Fajrul\AppData\Local\Temp\pip-req-build-jv4gf0hu\setup.py", line 198, in prep_mcp
        subprocess.check_call('{} clean build shadowJar'.format(gradlew).split(' '), cwd=workdir)
      File "c:\users\fajrul\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['gradlew.bat', 'clean', 'build', 'shadowJar']' returned non-zero exit status 1.
``

**Comment by Miffyli** [comment]
Double-check that you have java JDK 8 installed. Error says you have only JRE 8 installed.

**Comment by fajrulfx** [comment]
Thank you! I missed the JDK thing and only see the ``gradlew.bat`` at the end. Finally, I can correctly install it.
