### ISSUE TITLE
Terminating Minecraft reports ERROR logs

### ISSUE THREAD

**Issue by keisuke-nakata** [minerllabs/minerl#65]
I found the following ERROR logs when terminating Minecraft.  
Here is the last lines from my training script's log file:

```
ERROR    - 2019-06-19 00:48:57,097 - [minerl.env.malmo log_to_file 327] [00:48:57] [EnvServerSocketHandler/INFO]: [STDERR]: java.io.EOFException
ERROR    - 2019-06-19 00:48:57,097 - [minerl.env.malmo log_to_file 327] [00:48:57] [EnvServerSocketHandler/INFO]: [STDERR]: 	at java.io.DataInputStream.readInt(DataInputStream.java:392)
ERROR    - 2019-06-19 00:48:57,097 - [minerl.env.malmo log_to_file 327] [00:48:57] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer$1.run(MalmoEnvServer.java:147)
ERROR    - 2019-06-19 00:48:57,097 - [minerl.env.malmo log_to_file 327] [00:48:57] [EnvServerSocketHandler/INFO]: [STDERR]: java.io.EOFException
ERROR    - 2019-06-19 00:48:57,097 - [minerl.env.malmo log_to_file 327] [00:48:57] [EnvServerSocketHandler/INFO]: [STDERR]: 	at java.io.DataInputStream.readInt(DataInputStream.java:392)
ERROR    - 2019-06-19 00:48:57,097 - [minerl.env.malmo log_to_file 327] [00:48:57] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer$1.run(MalmoEnvServer.java:147)
ERROR    - 2019-06-19 00:48:57,097 - [minerl.env.malmo log_to_file 327] [00:48:57] [EnvServerSocketHandler/INFO]: [STDOUT]: [ERROR] MalmoEnv socket error: java.io.EOFException (can be on disconnect)
ERROR    - 2019-06-19 00:48:57,097 - [minerl.env.malmo log_to_file 327] [00:48:57] [EnvServerSocketHandler/INFO]: [STDOUT]: [ERROR] MalmoEnv socket error: java.io.EOFException (can be on disconnect)
INFO     - 2019-06-19 00:48:57,097 - [minerl.env.malmo log_to_file 329] [00:48:57] [EnvServerSocketHandler/INFO]: [STDOUT]: [LOGTOPY] Want to quit on disconnect.
ERROR    - 2019-06-19 00:48:57,117 - [minerl.env.malmo log_to_file 327] [00:48:57] [Client thread/INFO]: [STDOUT]: STATE ERROR - multiple states in the queue.
INFO     - 2019-06-19 00:49:00,115 - [minerl.env.malmo on_terminate 200] Minecraft process psutil.Process(pid=293, status='terminated') terminated with exit code 0
```

The exit code for the Python process was `0` (= SUCCESS), so these error logs don't seem errors.  
This issue never prevent training/evaluation for RL agents, though. (Just a noise.)

Python 3.6, MineRL 0.1.10 (commit `ac59d1fe08175ae574c02bd69e3437902ddfb8fc`)

**Comment by DazaiSan** [comment]
I am encountering similar error possibly 
`[22:32:16] [EnvServerSocketHandler/INFO]: [STDERR]: java.io.EOFException
[22:32:16] [EnvServerSocketHandler/INFO]: [STDERR]: 	at java.io.DataInputStream.readInt(DataInputStream.java:392)
[22:32:16] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer$1.run(MalmoEnvServer.java:147)
[22:32:16] [EnvServerSocketHandler/INFO]: [STDOUT]: [ERROR] MalmoEnv socket error: java.io.EOFException (can be on disconnect)
[22:32:16] [EnvServerSocketHandler/INFO]: [STDERR]: java.io.EOFException
[22:32:16] [EnvServerSocketHandler/INFO]: [STDERR]: 	at java.io.DataInputStream.readInt(DataInputStream.java:392)
[22:32:16] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer$1.run(MalmoEnvServer.java:147)
[22:32:16] [EnvServerSocketHandler/INFO]: [STDOUT]: [ERROR] MalmoEnv socket error: java.io.EOFException (can be on disconnect)
[Finished in 64.6s]`
