### ISSUE TITLE
Charcoal smelting 

### ISSUE THREAD

**Issue by nhsjdiwlcnsv** [minerllabs/minerl#658]
Hello. While programming on MineRL v0.4.4 I've encountered a problem with smelting. Maybe I have misunderstood the information at https://minerl.readthedocs.io/en/v0.4.4/environments/index.html#minerlobtaindiamond-v0 but as far as I can tell there is an action for `MineRLObtainDiamond-v0` that allows me to smelt charcoal from tree logs (it is stated in the following piece of code):
```
Dict({
    "attack": "Discrete(2)",
    "back": "Discrete(2)",
    "camera": "Box(low=-180.0, high=180.0, shape=(2,))",
    "craft": "Enum(crafting_table,none,planks,stick,torch)",
    "equip": "Enum(air,iron_axe,iron_pickaxe,none,stone_axe,stone_pickaxe,wooden_axe,wooden_pickaxe)",
    "forward": "Discrete(2)",
    "jump": "Discrete(2)",
    "left": "Discrete(2)",
    "nearbyCraft": "Enum(furnace,iron_axe,iron_pickaxe,none,stone_axe,stone_pickaxe,wooden_axe,wooden_pickaxe)",
    "nearbySmelt": "Enum(coal,iron_ingot,none)",
    "place": "Enum(cobblestone,crafting_table,dirt,furnace,none,stone,torch)",
    "right": "Discrete(2)",
    "sneak": "Discrete(2)",
    "sprint": "Discrete(2)"
})
```
However, when I place the furnace and try to smelt logs into coal (having such fuel as planks and sticks and even a wooden pickaxe) I get no coal and all the items in my inventory remain in the same amounts.

What am I doing wrong?

**Comment by Miffyli** [comment]
This is an [old bug](https://discourse.aicrowd.com/t/how-to-use-furnace-to-nearbysmelt-coal/1970/7) that never unfortunately got fixed 😅 . It might be with the name "coal" used instead of "charcoal" to identify the object, as they are two different objects.

I would skip this part and use some other items to do smelting (e.g. wood directly).

**Comment by nhsjdiwlcnsv** [comment]
Thanks for your answer!! I can't use any other items because I actually need to create torches before going underground, but I think that I'll figure it out somehow😼
