### ISSUE TITLE
Camera values outside the interval

### ISSUE THREAD

**Issue by marioyc** [minerllabs/minerl#66]
There's data where the second camera coordinate is outside the [-180,180] interval contrary to what's specified [here](https://github.com/minerllabs/minerl/blob/master/minerl/env/__init__.py#L49)

For example, for Treechop, we have:

> r2g1alarming_arugula_medusa-12_60585-61411 (827 frames)
camera0: min=-82.05001068115234 (Frame 1), max=1.6500000953674316 (Frame 8)
camera1: min=-183.29974365234375 (Frame 1), max=1.7999999523162842 (Frame 8)

>r2g1extroverted_broccoli_griffin-4_6992-7666 (675 frames)
camera0: min=-10.200002670288086 (Frame 407), max=11.25 (Frame 437)
camera1: min=-703.4344482421875 (Frame 2), max=55.650001525878906 (Frame 98)

>r2g1sticky_chick_pea_gnome-16_3545-5489 (1945 frames)
camera0: min=-105.75 (Frame 1629), max=70.79999542236328 (Frame 137)
camera1: min=-48.149993896484375 (Frame 825), max=984.045654296875 (Frame 2)

>r2g1absolute_grape_changeling-15_5572-7668 (2097 frames)
camera0: min=-79.3499984741211 (Frame 1941), max=64.5 (Frame 231)
camera1: min=-384.90008544921875 (Frame 1), max=72.60000610351562 (Frame 1512)

>r2g1tempting_capers_shapeshifter-14_12243-16213 (3971 frames)
camera0: min=-105.30882263183594 (Frame 1964), max=96.33769226074219 (Frame 2044)
camera1: min=-179.41265869140625 (Frame 985), max=360.0006103515625 (Frame 2222)

>r2g1hoarse_watermelon_gargoyle-18_4757-5329 (573 frames)
camera0: min=-79.35010528564453 (Frame 1), max=11.549999237060547 (Frame 540)
camera1: min=-266.54931640625 (Frame 1), max=30.449951171875 (Frame 539)

>r2g1subtle_iceberg_lettuce_nymph-6_9809-11841 (2033 frames)
camera0: min=-66.9000015258789 (Frame 435), max=38.84999084472656 (Frame 1191)
camera1: min=-60.449981689453125 (Frame 700), max=738.307861328125 (Frame 1929)

>r2g1ugly_cress_orc-13_2530-2844 (315 frames)
camera0: min=-78.5999984741211 (Frame 1), max=18.450000762939453 (Frame 279)
camera1: min=-365.54998779296875 (Frame 1), max=19.950000762939453 (Frame 21)

>r2g1subtle_iceberg_lettuce_nymph-6_3819-6067 (2249 frames)
camera0: min=-66.75 (Frame 531), max=41.39999771118164 (Frame 1052)
camera1: min=-42.75 (Frame 1695), max=249.75213623046875 (Frame 1672)

>r2g1cool_sweet_potato_nymph-13_724-5562 (4839 frames)
camera0: min=-32.400001525878906 (Frame 2534), max=39.45003128051758 (Frame 1923)
camera1: min=-362.70001220703125 (Frame 1), max=232.80084228515625 (Frame 4185)

As it can be observed some of these happen during the initial frames, which could be related the initial teleportation that seems to be going on, but there are also cases like `r2g1cool_sweet_potato_nymph-13_724-5562` where the player should be the one controlling it.

Is it okay that this is happening? if so, then, is it possible to give another fixed range where the values would definitely be contained?

Also, are the actions recorded during the teleportation? and, do they have any effect?

**Comment by brandonhoughton** [comment]
Thank you again for finding this - this has been fixed and we will integrate the change into the next release of the data!
