### ISSUE TITLE
Installation error. java.util.zip.ZipException

### ISSUE THREAD

**Issue by guichristmann** [minerllabs/minerl#660]
Hi, I'm trying to install the MineRL environment according to the instructions using `pip install git+https://github.com/minerllabs/minerl --user`. I've made sure that my java version is 1.8.xxx. Running the setup.py results in a huge error log. At the very top the error reads:
`Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file`.

I've tried poking around with other java versions and installing from the repo or with the git link, but no success yet.
Any ideas? Appreciate any help on this matter.

Full error log attached as a text file.

[error_log.txt](https://github.com/minerllabs/minerl/files/9299273/error_log.txt)

**Comment by Miffyli** [comment]
Hmm interesting error, I have not encountered this before. The error could be in a corrupted download and the cached zip file is unopenable, but that should be downloaded every time you try to install things, especially with `pip install git+...`.

Do you happen to have gradle installed on your machine somewhere? Removing that and any cached .gradle files (e.g. in the home directory) might help. Something along those lines [here](https://github.com/flutter/flutter/issues/51195). You could also try cloning the repository and running `pip install .`: probably won't help, but might give more insight what is happening.

**Comment by guichristmann** [comment]
I have no idea what was the issue other than it was related to Gradle. Following your suggestion, I deleted every single instance of gradle related directories that I could find with: `find / -name gradle`. After that, running the pip install again works as intended.

Thanks for your help, cheers.
