### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by ChickenNuggetsK** [minerllabs/minerl#663]
I have some littles errors when I use `pip install git+https://github.com/minerllabs/minerl --user`, here is the output (In a file to bypass characters limit)

[output.txt](https://github.com/minerllabs/minerl/files/9438604/output.txt)

Good luck to read this!

System specifications:
OS: Windows 11 home (I run the command using wsl and debian)
Java version (wsl): 1.8.0 332
Javac version (wsl): 1.8.0 332
Java version (windows): 1.8.0 341
Javac version (windows): 1.8.0 341

And I already have disabled path characters limit

(Sorry for the english, I'm french)

**Comment by Miffyli** [comment]
Quick search on google for exit code 137 indicates it was an out-of-memory error. How much RAM do you have on your machine? This compilation process can take quite a bit of memory. WSL by default has quite a limited amount of RAM available to it.

**Comment by ChickenNuggetsK** [comment]
I tried with 5go and it works, thank you very much!
