### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by VedikaSrivastava** [minerllabs/minerl#668]
while running the command `pip install git+https://github.com/minerllabs/minerl` i am getting the following errors.

`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\akalps\\AppData\\Local\\Temp\\pip-req-build-6hpfjd7z\\scripts' `

I am using Windows 10 64-bit

**Comment by VedikaSrivastava** [comment]
Simply reinstalling worked for me

**Comment by bchen0** [comment]
Hi @VedikaSrivastava - do you remember what you reinstalled? I am getting the same error and was wondering if you remembered how you fixed it

**Comment by VedikaSrivastava** [comment]
I don't remember very well, but I think I had reinstalled WSL and Ubuntu.
