### ISSUE TITLE
Invalid values in enum fields

### ISSUE THREAD

**Issue by marioyc** [minerllabs/minerl#67]
There are cases where the action craft has values 4 or 5 in the data (besides 0,2,3 which are valid), but the documentation says craft is an enum with 4 values ("craft": "Enum(none,torch,stick,planks)") hence the values should be 0,1,2 or 3.

Similarly there is equip with value 6, nearbyCraft with value 8, nearbySmelt with value 3, and place with value 6.

Is this an error on the documentation or the data?

**Comment by brandonhoughton** [comment]
The documentation must be stale here; previously we did not allow crafting of a crafting table, and other items were added to allow agents to craft other tools such as an iron axe

**Comment by marioyc** [comment]
Got it, indeed the documentation doesn't show the crafting table on the enum field.

So, for example for the field "craft": "Enum(none,torch,stick,planks)", is the mapping: none->1, torch->2, stick->3, planks->4 ?
From the [code](https://github.com/minerllabs/minerl/blob/master/minerl/env/spaces.py#L42) it seems like the value 0 is used for a no-op, what would be the difference between this no-op and the "none" action in the enum fields?
