### ISSUE TITLE
Is there anyway to create a Custom Environment now?

### ISSUE THREAD

**Issue by mwang808** [minerllabs/minerl#673]
I remember there was a tutorial on creating a custom environment. Does it still work now?

**Comment by Miffyli** [comment]
Hey! The tutorial still lives [here](https://minerl.readthedocs.io/en/v0.4.4/tutorials/custom_environments.html) and is valid for MineRL v0.4.4, which you can install from pypi with `pip install minerl==0.4.4`. This current version on github is v1.0 and it does not have the same tools for creating scenarios.

**Comment by mwang808** [comment]
Thanks. It works.
