### ISSUE TITLE
How to change gamma in v0.4.4?

### ISSUE THREAD

**Issue by danijar** [minerllabs/minerl#680]
Hi, I would like to change some game settings, especially `ao`, `fovEffectScale`, and `gamma` in [options.txt](https://minecraft.fandom.com/wiki/Options.txt).

I have been using v0.4.4 until now because it includes `options.txt` in the pip installation, so it was easy for me to change `ao` and `fovEffectScale`. However, setting `gamma` in the options file didn't affect the brightness and I think gamma was somehow fixed to a value of around 2. Is there a way to override the gamma setting in v0.4.4?

Thanks!

**Comment by Miffyli** [comment]
Looks like Malmo [fixes the gamma to 2.0](https://github.com/minerllabs/minerl/blob/v0.4/minerl/Malmo/Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java#L1876). Removing that line from the Java side and building the java side (I would personally do `pip install .`) should do the trick :)

(Edit: totally did not figure out this for [v1.0 as well](https://github.com/minerllabs/minerl/tree/miffyli/options-txt-support) before noticing your edit, but at least now I know v1.0 skips options.txt completely unless you modify the code)

**Comment by danijar** [comment]
Great, thanks! I'm running with it now, just have to wait until the agent starts digging underground to tell if it worked.

**Comment by danijar** [comment]
That worked, thanks a lot @Miffyli!
