### ISSUE TITLE
How to see sugar_cane in the inventory?

### ISSUE THREAD

**Issue by danijar** [minerllabs/minerl#683]
Hi, I noticed that `MC_ITEM_IDS` in `mc.py` contains `minecraft:reeds` but not `minecraft:sugar_cane`. According to the [Minecraft Wiki](https://minecraft.fandom.com/wiki/Sugar_Cane), `reeds` is the name of the (ungivable) block whereas `sugar_cane` is the item name you obtain from breaking it. Is that a mistake in MineRL (v0.4.4)?

I tried just adding `minecraft:sugar_cane` to the Python list but it still doesn't show up in the inventory observation.

Thanks!

**Comment by Miffyli** [comment]
Quickly testing giving player `reeds` and dropping it, looks like it is sugar cane (albeit I do not know what `reeds` object looks like if dropped) :) . Looks like this is some kind of a typo in MineRL. I would still try to double-confirm that this `reeds` works like sugar cane (e.g., you can plant it next to water).
![image](https://user-images.githubusercontent.com/1633800/200661059-8621b87f-a9ca-4b7e-a376-6b734a82bb70.png)

**Comment by danijar** [comment]
Great, so it's probably just sugar cane and just the text label is off. I'll use that for now and see if the agent ends up being able to craft books from it.
