### ISSUE TITLE
Issue installing minerl: error: metadata-generation-failed

### ISSUE THREAD

**Issue by 4mnestic** [minerllabs/minerl#685]
Issue installing minerl. I've attached logs.

[extralog.txt](https://github.com/minerllabs/minerl/files/10232315/extralog.txt)
[log.txt](https://github.com/minerllabs/minerl/files/10232317/log.txt)

**Comment by Miffyli** [comment]
Hard to say what the error exactly is, but usual culprit is invalid java installation. Make sure you have installed full JDK 8 (and that machine is using it with checking version with `java -version`), and that you installed x64 version.

**Comment by 4mnestic** [comment]
(base) zachary@Lizard-3 ~ % java -version
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

Is this what I want to see?

Edit: also this is odd...

(base) zachary@Lizard-3 ~ % which java      
/usr/bin/java
(base) zachary@Lizard-3 ~ % cd /usr/bin/java
cd: not a directory: /usr/bin/java
(base) zachary@Lizard-3 ~ % cd /usr/bin/    
(base) zachary@Lizard-3 bin % cd java         
cd: not a directory: java

I'm running MacOS on a 2020 MacBook Pro, for the record.

**Comment by Miffyli** [comment]
Oh, the newest version of MineRL does not work on Macs unfortunately :(. You might get the older versions working, though (see README.md about the versions). As a sidenote, the Java version is off indeed; it should say something akin to "1.8...." instead of "17.0.2".

**Comment by 4mnestic** [comment]
Ah, okay! Thanks for the help!
