### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by turtlemaster890** [minerllabs/minerl#689]
[error.txt](https://github.com/minerllabs/minerl/files/10452262/error.txt)

**Comment by Miffyli** [comment]
The error suggests you do not have JDK 8 installed. The installed Java versions have to be JDK 8 specifically. If you have other java installations on your machine on Windows, the best option is to uninstall everything and then only install JDK 8.

**Comment by turtlemaster890** [comment]
it worked thanks!
