### ISSUE TITLE
Error while trying to install package

### ISSUE THREAD

**Issue by Niroxbtw** [minerllabs/minerl#709]
Collecting git+https://github.com/minerllabs/minerl
  Cloning https://github.com/minerllabs/minerl to c:\users\user\appdata\local\temp\pip-req-build-it_d7qqc
  Running command git clone --filter=blob:none --quiet https://github.com/minerllabs/minerl 'C:\Users\user\AppData\Local\Temp\pip-req-build-it_d7qqc'
  Resolved https://github.com/minerllabs/minerl to commit 20d53e40fe2eba22545308e9d0473427f8f523dd
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [129 lines of output]
      Cloning into 'MCP-Reborn'...
      Note: switching to '1.16.5-20210115'.
     
      You are in 'detached HEAD' state. You can look around, make experimental
      changes and commit them, and you can discard any commits you make in this
      state without impacting any branches by switching back to a branch.
     
      If you want to create a new branch to retain commits you create, you may
      do so (now or later) by using -c with the switch command. Example:
     
        git switch -c <new-branch-name>
     
      Or undo this operation with:
     
        git switch -
     
      Turn off this advice by setting config variable advice.detachedHead to false
     
      HEAD is now at 1e71be5 Update README.md
     
      > Configure project :
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_1339809166 -> downloads to: /C:/Users/user/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_1339809166 -> downloads to: /C:/Users/user/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
     
      > Task :verifyRepos
      Checking BuildScript Repositories:
       | - [ OK ]: MavenLocal -> file:/C:/Users/user/.m2/repository/
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
      Checking Project Repositories:
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
       | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
       | - [ OK ]: BUNDELED_1339809166 (accepted custom MC repo)
       | - [FAIL]: maven3 -> https://libraries.minecraft.net/
     
      > Task :downloadMCMeta
      > Task :downloadAssets
     
      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings
     
      BUILD SUCCESSFUL in 18s
      3 actionable tasks: 3 executed
     
      > Configure project :
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-2067506848 -> downloads to: /C:/Users/user/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-2067506848 -> downloads to: /C:/Users/user/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
     
      > Task :verifyRepos
      Checking BuildScript Repositories:
       | - [ OK ]: MavenLocal -> file:/C:/Users/user/.m2/repository/
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
      Checking Project Repositories:
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
       | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
       | - [ OK ]: BUNDELED_-2067506848 (accepted custom MC repo)
       | - [FAIL]: maven3 -> https://libraries.minecraft.net/
     
      > Task :clean
      > Task :deleteSchemas
      > Task :copySchemas
      > Task :jaxb
     
      > Task :compileJava
      Note: Some input files use or override a deprecated API.
      Note: Recompile with -Xlint:deprecation for details.
      Note: Some input files use unchecked or unsafe operations.
      Note: Recompile with -Xlint:unchecked for details.
     
      > Task :processResources
      > Task :createProperties
      > Task :classes
      > Task :jar
      > Task :assemble
      > Task :compileTestJava NO-SOURCE
      > Task :processTestResources NO-SOURCE
      > Task :testClasses
      > Task :test NO-SOURCE
      > Task :check
      > Task :build
      > Task :shadowJar
     
      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings
     
      BUILD SUCCESSFUL in 1m 49s
      10 actionable tasks: 10 executed
             ^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Miffyli** [comment]
Hey, looks like things actually worked out right. Can you copy-paste the _full_ error log? 

Edit: I applied a fix. Try installing now.

**Comment by JD-The-65th** [comment]
This is the same error I'm getting, even after the fix is applied.

**Comment by Niroxbtw** [comment]
Thank you for the response. I ran into a PermissionError: [WinError 32] . Rerunning to see if that changes anything. It takes very long to execute each time though. It seems to always take ages at: Preparing metadata (setup.py) ... \

**Comment by JD-The-65th** [comment]
~~I think I have a lead?~~

~~One of the errors is `java.lang.IllegalArgumentException: Unsupported class file major version 61`~~

~~I did some googling, and version 61 is associated with Java 17, so I'm gonna switch to java 17 and see if that does anything.~~

mmkay Ignore this, same error occurred.

**Comment by JD-The-65th** [comment]
OK, after setting the JAVA_HOME env variable to my Java 8 path (/usr/lib/jvm/java-8-openjdk), it didn't error out immediately.

**Comment by Niroxbtw** [comment]
So @Miffyli i retried and everything works now. Thank you very much for your effort

**Comment by JD-The-65th** [comment]
Oops, as it turns out this issue was not related to my issue at all o_o 😅
