### ISSUE TITLE
Problems installing MineRL package on Ubuntu 23.04

### ISSUE THREAD

**Issue by Sanfee18** [minerllabs/minerl#710]
Hi, I wanted to know if MineRL is working on Ubuntu 23.04 (Lunar Lobster).
No matters what I try, it allways gives this error:

`pip install git+https://github.com/minerllabs/minerl
Collecting git+https://github.com/minerllabs/minerl
  Cloning https://github.com/minerllabs/minerl to /tmp/pip-req-build-3d38_l2y
  Running command git clone --filter=blob:none --quiet https://github.com/minerllabs/minerl /tmp/pip-req-build-3d38_l2y
  Resolved https://github.com/minerllabs/minerl to commit 20d53e40fe2eba22545308e9d0473427f8f523dd
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [160 lines of output]
      Clonando en 'MCP-Reborn'...
      Nota: cambiando a '1.16.5-20210115'.
      
      Te encuentras en estado 'detached HEAD'. Puedes revisar por aquí, hacer
      cambios experimentales y hacer commits, y puedes descartar cualquier
      commit que hayas hecho en este estado sin impactar a tu rama realizando
      otro checkout.
      
      Si quieres crear una nueva rama para mantener los commits que has creado,
      puedes hacerlo (ahora o después) usando -c con el comando checkout. Ejemplo:
      
        git switch -c <nombre-de-nueva-rama>
      
      O deshacer la operación con:
      
        git switch -
      
      Desactiva este aviso poniendo la variable de config advice.detachedHead en false
      
      HEAD está ahora en 1e71be5 Update README.md
      Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
      > Task :mcp:downloadConfig
      
      > Task :mcp:setupMCP
      Setting up MCP environment
      Initializing steps
      Executing steps
       > Running 'downloadManifest'
       > Running 'downloadJson'
       > Running 'downloadClient'
       > Running 'downloadServer'
       > Running 'stripClient'
       > Running 'stripServer'
       > Running 'merge'
       > Running 'rename'
       > Running 'mcinject'
       > Running 'listLibraries'
       > Running 'decompile'
       > Running 'inject'
       > Running 'patch'
      MCP environment setup is complete
      
      > Task :applyPatches
      > Task :downloadMappings
      > Task :srg2mcp
      > Task :extractMapped
      > Task :setup
      
      BUILD SUCCESSFUL in 2m 4s
      6 actionable tasks: 6 executed
      Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
      
      > Configure project :
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-1307739280 -> downloads to: /home/sanfe/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-1307739280 -> downloads to: /home/sanfe/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      
      > Task :verifyRepos
      Checking BuildScript Repositories:
       | - [ OK ]: MavenLocal -> file:/home/sanfe/.m2/repository
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
      Checking Project Repositories:
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
       | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
       | - [ OK ]: BUNDELED_-1307739280 (accepted custom MC repo)
       | - [FAIL]: maven3 -> https://libraries.minecraft.net/
      
      > Task :downloadMCMeta
      > Task :downloadAssets
      
      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings
      
      BUILD SUCCESSFUL in 14s
      3 actionable tasks: 3 executed
      
      > Configure project :
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_1725459069 -> downloads to: /home/sanfe/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_1725459069 -> downloads to: /home/sanfe/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      
      > Task :verifyRepos
      Checking BuildScript Repositories:
       | - [ OK ]: MavenLocal -> file:/home/sanfe/.m2/repository
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
      Checking Project Repositories:
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
       | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
       | - [ OK ]: BUNDELED_1725459069 (accepted custom MC repo)
       | - [FAIL]: maven3 -> https://libraries.minecraft.net/
      
      > Task :clean
      > Task :deleteSchemas
      > Task :copySchemas
      > Task :jaxb
      > Task :compileJava
      Note: Some input files use or override a deprecated API.
      Note: Recompile with -Xlint:deprecation for details.
      Note: Some input files use unchecked or unsafe operations.
      Note: Recompile with -Xlint:unchecked for details.
      
      > Task :processResources
      > Task :createProperties
      > Task :classes
      > Task :jar
      > Task :assemble
      > Task :compileTestJava NO-SOURCE
      > Task :processTestResources NO-SOURCE
      > Task :testClasses
      > Task :test NO-SOURCE
      > Task :check
      > Task :build
      > Task :shadowJar
      
      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings
      
      BUILD SUCCESSFUL in 1m 43s
      10 actionable tasks: 10 executed
      error in minerl setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
          git+https://github.com/minerllabs/gym@minerl-fix
             ^
      [end of output]`

**Comment by Miffyli** [comment]
Ugh... I thought I had fixed this. Can you provide the Python version you are using so I can try to replicate this? 

Edit: Ah I see the issue. Fixing it!
Edit2: Can you try installing it now?

**Comment by Sanfee18** [comment]
Yes, it worked now!
You are the goat dude, thank you so much! <3
