### ISSUE TITLE
Issue installing MineRL package on M2 Macbook

### ISSUE THREAD

**Issue by Sanfee18** [minerllabs/minerl#715]
Hi, I'm having the following problem installing MineRL package on MacOs:

(MineRL) davidsanfelix@wifialu50-31 TFG % pip install git+https://github.com/minerllabs/minerl
Collecting git+https://github.com/minerllabs/minerl
  Cloning https://github.com/minerllabs/minerl to /private/var/folders/jt/m_8kzsgx4f1_3gbm5ddq9_380000gn/T/pip-req-build-jwmhpqgu
  Running command git clone --filter=blob:none --quiet https://github.com/minerllabs/minerl /private/var/folders/jt/m_8kzsgx4f1_3gbm5ddq9_380000gn/T/pip-req-build-jwmhpqgu
  Resolved https://github.com/minerllabs/minerl to commit c0c9baa03b5306ffc3acddc849ec4141b6deb98e
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2800 lines of output]
      Cloning into 'MCP-Reborn'...
      Note: switching to '1.16.5-20210115'.
      
      You are in 'detached HEAD' state. You can look around, make experimental
      changes and commit them, and you can discard any commits you make in this
      state without impacting any branches by switching back to a branch.
      
      If you want to create a new branch to retain commits you create, you may
      do so (now or later) by using -c with the switch command. Example:
      
        git switch -c <new-branch-name>
      
      Or undo this operation with:
      
        git switch -
      
      Turn off this advice by setting config variable advice.detachedHead to false
      
      HEAD is now at 1e71be5 Update README.md
      > Task :mcp:downloadConfig
      
      > Task :mcp:setupMCP
      Setting up MCP environment
      Initializing steps
      Executing steps
       > Running 'downloadManifest'
       > Running 'downloadJson'
       > Running 'downloadClient'
       > Running 'downloadServer'
       > Running 'stripClient'
       > Running 'stripServer'
       > Running 'merge'
       > Running 'rename'
       > Running 'mcinject'
       > Running 'listLibraries'
       > Running 'decompile'
       > Running 'inject'
       > Running 'patch'
      MCP environment setup is complete
      
      > Task :applyPatches
      > Task :downloadMappings
      > Task :srg2mcp
      > Task :extractMapped
      > Task :setup
      
      BUILD SUCCESSFUL in 2m 21s
      6 actionable tasks: 6 executed
      Downloading https://services.gradle.org/distributions/gradle-6.8.1-bin.zip
      ......................................................................................................
      
      Welcome to Gradle 6.8.1!
      
      Here are the highlights of this release:
       - Faster Kotlin DSL script compilation
       - Vendor selection for Java toolchains
       - Convenient execution of tasks in composite builds
       - Consistent dependency resolution
      
      For more details see https://docs.gradle.org/6.8.1/release-notes.html
      
      Starting a Gradle Daemon (subsequent builds will be faster)
      
      > Configure project :
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_1837748836 -> downloads to: /Users/davidsanfelix/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_1837748836 -> downloads to: /Users/davidsanfelix/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      
      > Task :verifyRepos
      Checking BuildScript Repositories:
       | - [ OK ]: MavenLocal -> file:/Users/davidsanfelix/.m2/repository
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
      Checking Project Repositories:
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
       | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
       | - [ OK ]: BUNDELED_1837748836 (accepted custom MC repo)
       | - [FAIL]: maven3 -> https://libraries.minecraft.net/
      
      > Task :downloadMCMeta
      Downloading: https://resources.download.minecraft.net/af/af96f55a90eaf11b327f1b5f8834a051027dc506 Asset: icons/icon_32x32.png
     (Sanfe18: Avoided for length reasons)
      Downloading: https://resources.download.minecraft.net/c1/c106e5ef000809049ce7d56e858898255cff9223 Asset: realms/textures/gui/images/9.png
      
      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings
      
      BUILD SUCCESSFUL in 1m 27s
      3 actionable tasks: 3 executed
      
      > Configure project :
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_2145065257 -> downloads to: /Users/davidsanfelix/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_2145065257 -> downloads to: /Users/davidsanfelix/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      
      > Task :verifyRepos
      Checking BuildScript Repositories:
       | - [ OK ]: MavenLocal -> file:/Users/davidsanfelix/.m2/repository
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
      Checking Project Repositories:
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
       | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
       | - [ OK ]: BUNDELED_2145065257 (accepted custom MC repo)
       | - [FAIL]: maven3 -> https://libraries.minecraft.net/
      
      > Task :clean
      > Task :deleteSchemas
      > Task :copySchemas
      > Task :jaxb
      > Task :compileJava FAILED
      
      FAILURE: Build failed with an exception.
      
      * What went wrong:
      Execution failed for task ':compileJava'.
      > Could not find tools.jar. Please check that /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home contains a valid JDK installation.
      
      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
      
      * Get more help at https://help.gradle.org
      
      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings
      
      BUILD FAILED in 59s
      6 actionable tasks: 6 executed
      Traceback (most recent call last):
        File "/Users/davidsanfelix/Documents/TFG/MineRL/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/davidsanfelix/Documents/TFG/MineRL/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/davidsanfelix/Documents/TFG/MineRL/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/jt/m_8kzsgx4f1_3gbm5ddq9_380000gn/T/pip-build-env-jo7jek9l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/jt/m_8kzsgx4f1_3gbm5ddq9_380000gn/T/pip-build-env-jo7jek9l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/jt/m_8kzsgx4f1_3gbm5ddq9_380000gn/T/pip-build-env-jo7jek9l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/jt/m_8kzsgx4f1_3gbm5ddq9_380000gn/T/pip-build-env-jo7jek9l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 214, in <module>
        File "<string>", line 198, in prep_mcp
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./gradlew', 'clean', 'build', 'shadowJar']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(MineRL

**Comment by Sanfee18** [comment]
I have updated to python3.11 and I still get the same error

**Comment by Miffyli** [comment]
Try [these instructions](https://github.com/minerllabs/minerl/issues/659#issuecomment-1306635414).
