### ISSUE TITLE
 'downloadAssets' Gradle Error During Install

### ISSUE THREAD

**Issue by Bpoole908** [minerllabs/minerl#719]
I'm trying to install MineRL inside a Docker container but I keep getting the following error. The container has Ubuntu 20.04, internet connection and openjdk 8. I can't seem to get around this issue. Any help or recommendations would be great.

```
      FAILURE: Build failed with an exception.

      * What went wrong:
      Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

      * Get more help at https://help.gradle.org
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-9w45m7bz/setup.py", line 214, in <module>
          prep_mcp()
        File "/tmp/pip-req-build-9w45m7bz/setup.py", line 193, in prep_mcp
          raise e
        File "/tmp/pip-req-build-9w45m7bz/setup.py", line 190, in prep_mcp
          subprocess.check_call('{} downloadAssets'.format(gradlew).split(' '), cwd=workdir)
        File "/home/dev/miniconda/envs/minerl/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./gradlew', 'downloadAssets']' returned non-zero exit status 1.
```

**Comment by Miffyli** [comment]
Hmm have not encountered this before. [This](https://github.com/minerllabs/basalt-2022-behavioural-cloning-baseline/blob/main/Dockerfile) was the Dockerfile used in the MineRL competition that used this version of MineRL, and it worked fine. Might give some pointers. Apart from that this seems to be a gradle issue, so searching for gradle issues with docker might help.

**Comment by Bpoole908** [comment]
As note for anyone with this problem in the future. I was unable to get around it. The core of the issue seemed to be with conda as I was trying to install all the necessary packages through conda inside the docker container (as I didn't have access to the root user). The solution was just to remake the container installing the require packages through git.
