### ISSUE TITLE
Unable to Install mineRL on Windows 11 - FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by machmoon** [minerllabs/minerl#722]
Any guidance or assistance in troubleshooting and resolving this error would be greatly appreciated.

**[Description]** 

I am experiencing difficulties installing MineRL within my Conda environment on Windows 11. Despite multiple attempts to restart my computer, reinstall Java, reinstall WSL, I have been unable to successfully install MineRL. I have diligently followed the installation instructions from https://minerl.readthedocs.io/en/latest/tutorials/index.html. I am consistently receiving the "FileNotFoundError: [WinError 2] The system cannot find the file specified" error during the MineRL installation process.

**[Environment Details]**

- Operating System: Windows 11
- WSL Version: WSL 2
- Java Version in WSL 2: openjdk version "1.8.0_362"
- Java Compiler Version in WSL 2: javac 1.8.0_362
- Terminal Java Version: java 1.8.0_371 (x64)
- Terminal Java Compiler Version: javac 1.8.0_371 (x64)
- Python Version in Conda Environment: Python 3.9.17

**[Steps Taken]**
In addition to the installation attempts, I have taken the following steps:

- Added "C:\Program Files\Java\jdk-1.8\bin" and "C:\Program Files\Java\jre-1.8\bin" to the system path variables.
- Cleared the appdata local temp folder.
- Updated setup tools.
- Ran the command with the user flag.
- Removed the .gradle folder before each run.

**[Additional Information]**

- Using Administrator Command Prompt and Administrator PowerShell.
- The installation process takes approximately 1 hour to complete.
- Laptop specifications: 16GB RAM, RTX 4050.
- This is a new laptop.

I don't believe the issue is related to path length limitation. Additionally, I have attempted to install the same Java version (1.8.0_371) within the WSL environment to match the version used in my terminal. However, I was only able to install the closest available version, which is Java version 1.8.0_362. 

I’ve attached the error log below from running the `pip install git+https://github.com/minerllabs/minerl` command in Administrator Powershell and Administrator Command Prompt.

Thank you for your time and help. Please let me know if any further information is needed

[CMD MineRL Error Log.txt](https://github.com/minerllabs/minerl/files/12036458/CMD.MineRL.Error.Log.txt)
[PowerShell MineRL Error Log.txt](https://github.com/minerllabs/minerl/files/12036460/PowerShell.MineRL.Error.Log.txt)

**Comment by Miffyli** [comment]
Hey. The core problem seems to be that the env is using wrong Java installation (the "compileJava" error). The error also suggests it can not find JDK (only JRE). Make sure `javac -version` command works both inside WSL and Windows, and that they report version akin "1.8....". On WSL side it might have other java version, and you have to use following commands to change the "default" Java commands to use:

```
sudo update-alternatives --config java
sudo update-alternatives --config javac
```

**Comment by machmoon** [comment]
Hi Miffyli,

Thank you for your response. 

Within Windows java and javac report the same version (1.8.0_371). 

Within WSL java and javac report the same version as well (1.8.0_362). In WSL, there is only one alternative in /usr/bin/javac and /usr/bin/java and there is nothing to configure. I also wanted to let you know that I was only able to install 1.8.0_362 in WSL.

Thank you for your help. Please let me know if any other information is needed.

I've additionally attached the WSL and Windows Log of my java and javac versions and running the `sudo update-alternatives --config` command below.

[WSL Java & Javac.txt](https://github.com/minerllabs/minerl/files/12052961/WSL.Java.Javac.txt)
[WSL_MineRL.txt](https://github.com/minerllabs/minerl/files/12052962/WSL_MineRL.txt)

**Comment by Miffyli** [comment]
Hmm I would try running the MineRL installation on Windows side again. The original error suggests that there is another java installation that is confusing the system (`C:\Program Files\Java\jre-1.8`). You might want to delete all java installations and clean your env variables, and then _only_ install correct JDK. Avoid manually modifying env variables; they should be automatically set by the JDK installer.

**Comment by machmoon** [comment]
Hi Miffyli,

Thank you for your support.

I manually added javac to my env variables before. However, even after uninstalling java and reinstalling java (x64), the installation still didn't work. I have attempted to install mineRL multiple times. In between each install, I cleared my appdata local temp and removed .graddle (if present) and then restarted, and then installed mineRL in an administrator Command Prompt. make sure that only the terminal is running for the duration of the download. Each download takes over an hour still. 

InterestinI gly, the first time I attempted to install mineRL I received a different error log but the same ultimate issue. However, my attempts after had the same error log. I've attached my first error log "CMD Java Reinstall" and my last error log "CMD Java Reinstall 4" below. Additionally, javac is no longer recognized in Windows after removing java env variables and reinstalling java.

Thank you for your help and time.


[CMD Reinstall Java 4.txt](https://github.com/minerllabs/minerl/files/12060345/CMD.Reinstall.Java.4.txt)
[CMD Reinstall Java.txt](https://github.com/minerllabs/minerl/files/12060346/CMD.Reinstall.Java.txt)

**Comment by Miffyli** [comment]
You need to use Powershell to run the commands, I am not sure if command line has the "bash" call created by WSL installation (the latter error log suggests this happened there).

For first one, it suggests it is still trying to use JRE installation to build things, not JDK installation. Make sure to remove every Java installation (ideally using Windows's uninstall tool to cleanup everything), remove any env variables, and then install JDK from here: https://www.oracle.com/uk/java/technologies/javase/javase8u211-later-archive-downloads.html (I have 8u333 installed atm, if you want to try something that works on my machine). After installation and restart you should have valid `java` and `javac` commands, but if not, you might need to add the JDK path to environment path variables (e.g., `C:\Program Files\Java\jdk1.8.0_333\bin`).

To debug installation, you should not need to clean caches. As long as the errors are about Java failing to compile, these caches won't affect the result, and speed up your trials.

**Comment by machmoon** [comment]
Hi Miffyil,

I encountered the same error while trying to install the mineRL package using PowerShell as an administrator and JDK 8u333. Although the installation command failed with a `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\patri\\AppData\\Local\\Temp\\pip-req-build-iem585qn\\scripts'` error, I am currently able to run my mineRL script without any issues. If you have any insights on how to resolve the PermissionError issue, I would be grateful for your help.

Here are the steps I took, along with the corresponding images:

1. Uninstalled Existing Java Installation 
![Screenshot 2023-07-16 184702](https://github.com/minerllabs/minerl/assets/123125228/54146aee-5d00-41f9-9655-977f7a40a76e)
![Screenshot 2023-07-16 184752](https://github.com/minerllabs/minerl/assets/123125228/cf689977-8c5d-4683-bbb7-7517343f655c)

3. Removed Java Env Variables
![Screenshot 2023-07-16 185257](https://github.com/minerllabs/minerl/assets/123125228/14cb59dd-9402-480f-a431-09d784997d3f)

4. Installed JDK 8u333
![Screenshot 2023-07-16 185957](https://github.com/minerllabs/minerl/assets/123125228/195b4165-c4dd-40df-8578-c0d037c4ca6b)
![Screenshot 2023-07-16 190836](https://github.com/minerllabs/minerl/assets/123125228/75db3737-5fbb-449e-b38d-1e10c2dd56b8)

5. Restarted PC

6. Added the JDK path (C:\Program Files\Java\jdk1.8.0_333\bin) to the environment path variables in order to resolve the issue with the invalid javac command
[PS Javac Not Valid.txt](https://github.com/minerllabs/minerl/files/12072499/PS.Javac.Not.Valid.txt)
![Screenshot 2023-07-17 105458](https://github.com/minerllabs/minerl/assets/123125228/a7c2a218-ab80-47ef-98a4-298dc883e38c)

7. Restarted PC

8. Ran pip install git+https://github.com/minerllabs/minerl in Administrator PowerShell, but it failed.
[PS J 8u333.txt](https://github.com/minerllabs/minerl/files/12072622/PS.J.8u333.txt)

9. Restarted PC

10. Tried running pip install git+https://github.com/minerllabs/minerl in Administrator PowerShell again, but it failed.
[PS J 8u333 2.txt](https://github.com/minerllabs/minerl/files/12072621/PS.J.8u333.2.txt)

Despite the installation failures, the MineRL package and various dependencies were installed (see [PS Java 8u333 2.txt](https://github.com/minerllabs/minerl/files/12072621/PS.J.8u333.2.txt)). It's worth mentioning that the installation process of MineRL took several hours (approximately 2-3 hours). I have attached the error logs below:

[PS J 8u333 2.txt](https://github.com/minerllabs/minerl/files/12072621/PS.J.8u333.2.txt)
[PS J 8u333.txt](https://github.com/minerllabs/minerl/files/12072622/PS.J.8u333.txt)

I greatly appreciate your time, attention, and unwavering support throughout this troubleshooting process. Your invaluable assistance has been instrumental in helping me navigate this challenge. Thank you!

**Comment by Miffyli** [comment]
The second error log you attached indicates minerl was indeed installed correctly, but something failed in a cleanup phase. As long as you see log saying "succesfully installed ..." somewhere towards the end, it should be fine. I would try running MineRL scripts once that works out. 

The other error log gives an obscure "could not send message to gradle" error thing, which I have not seen before. This might be somehow related to the fact it takes 2-3 hours to install MineRL; your system might be running out memory or disk space (installation requires ideally at least 16GB RAM on the machine, especially if WSL is used).

Beyond that I am at a loss of help to give, as the errors are somewhat new and obscure (although still pointing at the java confusions) :( . It might help googling related issues in other Minecraft modding communities. Alternatively, installing MineRL purely on WSL (or Linux) should be much easier task.

**Comment by GF-Huang** [comment]
Excuse me, did you install conda in WSL2? Otherwise, how do you install bash on Win11?

**Comment by Miffyli** [comment]
WSL is the recommended way for "installing" bash on Windows, especially with MineRL. You can also install MineRL on the WSL itself, which will probably work out better.

**Comment by GF-Huang** [comment]
> WSL is the recommended way for "installing" bash on Windows, especially with MineRL. You can also install MineRL on the WSL itself, which will probably work out better.

Should I need to install the full Desktop environment for WSL2 Ubuntu? Or only the `xrdp`/`tightvnserver` is ok?

I had try the `tightvncserver`, but after connect, it show me the blank screen.

![image](https://github.com/minerllabs/minerl/assets/4510984/989465bb-4d40-429f-b38e-297070f4d7e0)

![image](https://github.com/minerllabs/minerl/assets/4510984/14dc7da9-c257-41af-9749-0cada822d9c1)

**Comment by GF-Huang** [comment]
Final, I got another command line environment via VNC. I'm not sure is this OK for MineRL/MineDojo.

![image](https://github.com/minerllabs/minerl/assets/4510984/d800a5f4-6221-4f16-b87a-98e64a459cf5)

![image](https://github.com/minerllabs/minerl/assets/4510984/08f387f3-34aa-4a2a-a133-f61485609eac)
