### ISSUE TITLE
Installation error: Execution failed for task ':mcp:setupMCP'.

### ISSUE THREAD

**Issue by MicycleBichael** [minerllabs/minerl#723]
I have all dependencies installed. This what i got from Powershell when I attempted to install:
[error.txt](https://github.com/minerllabs/minerl/files/12053428/error.txt)

**Comment by Miffyli** [comment]
Double-check your JDK installation. The "compileError" (towards end of the log) happens usually when wrong Java version is used. `javac -version` should report `1.8....`. You need JDK on both Windows and WSL side. Make sure to follow the instructions carefully in the docs: https://minerl.readthedocs.io/en/latest/tutorials/index.html

**Comment by MicycleBichael** [comment]
java -version and javac -version both report 1.8. Within WSL, both java -version and javac -version report 1.8. I have followed all instructions in the docs carefully.

**Comment by Miffyli** [comment]
Hmm hard to say what could be wrong in that case (the beginning of the log is also cut off, which might hide some info). Unfortunately the installation is pretty finnicky and sensitive to other installed things on system (e.g., gradle or sometimes other Java IDEs) that debugging these issues is very case-to-case matter, and the solution for one does not often work for others 😅  . Common tip I give is double check the Java installations (as you did) and that there is enough system resources to finish the compilation etc.

**Comment by MicycleBichael** [comment]
I'm pretty sure I have enough system resources to finish the compilation, how would I go about retrieving the whole log? I tried to do so but it seems there's a limit on how far back powershell was willing to let me see.

**Comment by Miffyli** [comment]
This command might help with logging powershell output: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript?view=powershell-7.3

**Comment by MicycleBichael** [comment]
I got a transcript of what should be the full log:
[transcript0.txt](https://github.com/minerllabs/minerl/files/12131030/transcript0.txt)

**Comment by Miffyli** [comment]
Seems like code is crashing to a weird java compilation error. [Quick googling](https://www.google.com/search?client=firefox-b-d&q=java+exit+value+137) of the error code (137) suggests it might be related to memory issues. Even if you have enough RAM on your main system side, your WSL setup might only have 50% of that (or less). Double-check that the WSL environment has at least 6GB available to it (or so).

**Comment by MicycleBichael** [comment]
I raised the ram available to WSL to 6GB and it seemed to go a lot more successfully, but an error popped up so I'm not sure if it installed correctly.
[transcript.txt](https://github.com/minerllabs/minerl/files/12152749/transcript.txt)

**Comment by Miffyli** [comment]
I think the package installed correctly but the cleanup phase failed for whatever reason (this sometimes happens on people). I'd recommend trying running MineRL now :)

**Comment by MicycleBichael** [comment]
It works! Thank you for helping!
