### ISSUE TITLE
HPC Cluster executions

### ISSUE THREAD

**Issue by Sanfee18** [minerllabs/minerl#731]
Hi,

I'm doing a research for my University Bachelor's Thesis on MineRL, mainly trying to use RL algorithms.

I'm having a lot of problems with time out errors that I'm trying to solve on another issue.

Right know I'm trying to execute my code via Singularity container, based on the docker containers for headless rendering from your documentation, on a HPC cluster, but I'm facing a lot of errors because of the inability to write files on host. Do you have any recommendations or related works? 

Thank you!

PD: By some executions I've been able to do, I haven't gotten any reward from the environment using PPO. I have some questions: Is it going to be possible to get any reward out of the environment? What is the best environment to try RL algorithms? Is Imitation Learning needed to see some progress on MineRL environments?

**Comment by Miffyli** [comment]
For Singularity: I think someone else brought up these issues, and I am not sure if there is a good solution for it (you may want to search issues for mentions of "Singularity" and see the discussions). 

As for getting results: RL alone will hardly cut it, usually the tasks require some imitation learning or some clever use. I recommend you check the [papers linked on MineRL webpage](https://minerl.readthedocs.io/en/latest/notes/useful-links.html), and also pay attention to new results like [Voyager](https://github.com/MineDojo/Voyager/) and Ghost in the Minecraft.

**Comment by Sanfee18** [comment]
Okay, thank you so much!
