### ISSUE TITLE
Data alignment of demonstrations

### ISSUE THREAD

**Issue by phidnight** [minerllabs/minerl#74]
In demonstrations, the number of frames in the record and that of actions in the log seems to be different (the former is larger).
And these records seem to contain several frames at the beginning in which a player is moving to an initial position.

Is it correct to concatenate frames and actions from the beginning frame? or do we need to skip first several frames?

**Comment by MadcowD** [comment]
There is a fix for this on the way! :)

**Comment by MadcowD** [comment]
@phidnight  Make sure to upgrade!
```
pip3 install --upgrade minerl
```
