### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by cdneeee** [minerllabs/minerl#743]
I am trying to run a basic environment  for Treechop, and I face this.
Tried couple things, but nothing worked so far.
Hope anyone here can help me, also I would appreciate any advices for the future. I've just started looking at this project.
Sometimes it gets stuck at line 61, sometimes at 53

RAM: 32GB
java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

1. Python 3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)] on win32
2. Type "help", "copyright", "credits" or "license" for more information.
3. >>> import minerl
4. >>> import gym
5. >>> import logging
6. >>> logging.basicConfig(level=logging.DEBUG)
7. >>> env = gym.make("MineRLTreechop-v0")
8. >>> obs = env.reset()
9. INFO:minerl.env.malmo.instance.eb2501:Starting Minecraft process: ['X:\\Code\\Conda\\lib\\site-packages\\minerl\\env\\..\\MCP-Reborn\\launchClient.bat', '-port', '11920', '-env', '-runDir', 'X:\\Code\\Conda\\lib\\site-packages\\minerl\\env\\..\\MCP-Reborn\\run']
10. INFO:process_watcher:Launching process watcher daemonizer.
11. X:\Code\Conda\lib\runpy.py:127: RuntimeWarning: 'minerl.utils.process_watcher' found in sys.modules after import of package 'minerl.utils', but prior to execution of 'minerl.utils.process_watcher'; this may result in unpredictable behaviour
12.   warn(RuntimeWarning(msg))
13. X:\Code\Conda\lib\runpy.py:127: RuntimeWarning: 'daemoniker._daemonize_windows' found in sys.modules after import of package 'daemoniker', but prior to execution of 'daemoniker._daemonize_windows'; this may result in unpredictable behaviour
14.   warn(RuntimeWarning(msg))
15. INFO:process_watcher:Process watcher daemonizer launched successfully.
16. DEBUG:minerl.env.malmo.instance.eb2501:SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
17. DEBUG:minerl.env.malmo.instance.eb2501:SLF4J: Defaulting to no-operation (NOP) logger implementation
18. DEBUG:minerl.env.malmo.instance.eb2501:SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
19. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:06] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
20. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:06] [Render thread/INFO]: Setting user: Player182
21. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:06] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
22. ERROR:minerl.env.malmo.instance.eb2501:[15:46:08] [Render thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'SAPIWrapper_x64': Can't obtain InputStream for win32-x86-64/SAPIWrapper_x64.dll
23. ERROR:minerl.env.malmo.instance.eb2501:ERROR : Couldn't load Narrator library : Unable to load library 'SAPIWrapper_x86': Can't obtain InputStream for win32-x86-64/SAPIWrapper_x86.dll
24. DEBUG:minerl.env.malmo.instance.eb2501:
25. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:09] [Render thread/INFO]: Reloading ResourceManager: Default
26. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:09] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
27. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:11] [Render thread/INFO]: OpenAL initialized.
28. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:11] [Render thread/INFO]: Sound engine started
29. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:12] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
30. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:12] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
31. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:12] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
32. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:12] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
33. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:12] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
34. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:12] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
35. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:12] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
36. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:12] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
37. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:12] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
38. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:12] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
39. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:13] [Thread-5/INFO]: [STDOUT]: ***** Start MalmoEnvServer on port 11920
40. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:13] [Thread-5/INFO]: [STDOUT]: CLIENT enter state: DORMANT
41. INFO:minerl.env.malmo.instance.eb2501:Minecraft process ready
42. DEBUG:minerl.env._multiagent:Creating socket connection Malmo[None:eb2501, proc=15460, addr=localhost:11920, locked=True]
43. INFO:minerl.env.malmo:Logging output of Minecraft to .\logs\mc_2920.log
44. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:13] [Thread-5/INFO]: [STDOUT]: SERVER enter state: DORMANT
45. DEBUG:minerl.env._multiagent:Saying hello for client: Malmo[None:eb2501, proc=15460, addr=localhost:11920, locked=True]
46. INFO:minerl.env._multiagent:Attempting to quit: Malmo[None:eb2501, proc=15460, addr=localhost:11920, locked=True]
47. DEBUG:minerl.env._multiagent:Sending mission init: Malmo[None:eb2501, proc=15460, addr=localhost:11920, locked=True]
48. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:13] [EnvServerSocketHandler/INFO]: Received Mission token 0bcf8f82-ed16-4486-ad80-f31cbd673776:0:0:1:true
49. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:13] [EnvServerSocketHandler/INFO]: Received mission init command  <MissionInit xmlns="http://ProjectMalmo.microsoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" SchemaVersion="" PlatformVersion="0.37.0"><Mission><About><Summary>MineRLTreechop-v0</Summary></About><ModSettings><MsPerTick>50</MsPerTick></ModSettings><ServerSection><ServerInitialConditions><Time><AllowPassageOfTime>false</AllowPassageOfTime></Time><AllowSpawning>true</AllowSpawning></ServerInitialConditions><ServerHandlers><DefaultWorldGenerator forceReset="true" generatorOptions="{&quot;coordinateScale&quot;:684.412,&quot;heightScale&quot;:684.412,&quot;lowerLimitScale&quot;:512.0,&quot;upperLimitScale&quot;:512.0,&quot;depthNoiseScaleX&quot;:200.0,&quot;depthNoiseScaleZ&quot;:200.0,&quot;depthNoiseScaleExponent&quot;:0.5,&quot;mainNoiseScaleX&quot;:80.0,&quot;mainNoiseScaleY&quot;:160.0,&quot;mainNoiseScaleZ&quot;:80.0,&quot;baseSize&quot;:8.5,&quot;stretchY&quot;:12.0,&quot;biomeDepthWeight&quot;:1.0,&quot;biomeDepthOffset&quot;:0.0,&quot;biomeScaleWeight&quot;:1.0,&quot;biomeScaleOffset&quot;:0.0,&quot;seaLevel&quot;:1,&quot;useCaves&quot;:false,&quot;useDungeons&quot;:false,&quot;dungeonChance&quot;:8,&quot;useStrongholds&quot;:false,&quot;useVillages&quot;:false,&quot;useMineShafts&quot;:false,&quot;useTemples&quot;:false,&quot;useMonuments&quot;:false,&quot;useMansions&quot;:false,&quot;useRavines&quot;:false,&quot;useWaterLakes&quot;:false,&quot;waterLakeChance&quot;:4,&quot;useLavaLakes&quot;:false,&quot;lavaLakeChance&quot;:80,&quot;useLavaOceans&quot;:false,&quot;fixedBiome&quot;:4,&quot;biomeSize&quot;:4,&quot;riverSize&quot;:1,&quot;dirtSize&quot;:33,&quot;dirtCount&quot;:10,&quot;dirtMinHeight&quot;:0,&quot;dirtMaxHeight&quot;:256,&quot;gravelSize&quot;:33,&quot;gravelCount&quot;:8,&quot;gravelMinHeight&quot;:0,&quot;gravelMaxHeight&quot;:256,&quot;graniteSize&quot;:33,&quot;graniteCount&quot;:10,&quot;graniteMinHeight&quot;:0,&quot;graniteMaxHeight&quot;:80,&quot;dioriteSize&quot;:33,&quot;dioriteCount&quot;:10,&quot;dioriteMinHeight&quot;:0,&quot;dioriteMaxHeight&quot;:80,&quot;andesiteSize&quot;:33,&quot;andesiteCount&quot;:10,&quot;andesiteMinHeight&quot;:0,&quot;andesiteMaxHeight&quot;:80,&quot;coalSize&quot;:17,&quot;coalCount&quot;:20,&quot;coalMinHeight&quot;:0,&quot;coalMaxHeight&quot;:128,&quot;ironSize&quot;:9,&quot;ironCount&quot;:20,&quot;ironMinHeight&quot;:0,&quot;ironMaxHeight&quot;:64,&quot;goldSize&quot;:9,&quot;goldCount&quot;:2,&quot;goldMinHeight&quot;:0,&quot;goldMaxHeight&quot;:32,&quot;redstoneSize&quot;:8,&quot;redstoneCount&quot;:8,&quot;redstoneMinHeight&quot;:0,&quot;redstoneMaxHeight&quot;:16,&quot;diamondSize&quot;:8,&quot;diamondCount&quot;:1,&quot;diamondMinHeight&quot;:0,&quot;diamondMaxHeight&quot;:16,&quot;lapisSize&quot;:7,&quot;lapisCount&quot;:1,&quot;lapisCenterHeight&quot;:16,&quot;lapisSpread&quot;:16}"/><ServerQuitFromTimeUp timeLimitMs="400000" description="out_of_time"/><ServerQuitWhenAnyAgentFinishes/></ServerHandlers></ServerSection><AgentSection mode="Survival"><Name>MineRLAgent0</Name><AgentStart><GuiScale>1.0</GuiScale><GammaSetting>2.0</GammaSetting><FOVSetting>70.0</FOVSetting><FakeCursorSize>16</FakeCursorSize><Inventory><InventoryObject slot="0" type="iron_axe" quantity="1"/></Inventory></AgentStart><AgentHandlers><FileBasedPerformanceProducer/><PauseCommand/><VideoProducer want_depth="false"><Width>64</Width><Height>64</Height></VideoProducer><HumanLevelCommands/><CameraCommands/><RewardForPossessingItem sparse="false" excludeLoops="true"><Item amount="1" reward="1.0" type="log"/></RewardForPossessingItem><AgentQuitFromPossessingItem><Item type="log" amount="64"/></AgentQuitFromPossessingItem></AgentHandlers></AgentSection></Mission><ExperimentUID>0bcf8f82-ed16-4486-ad80-f31cbd673776</ExperimentUID><ClientRole>0</ClientRole><ClientAgentConnection><ClientIPAddress>127.0.0.1</ClientIPAddress><ClientMissionControlPort>0</ClientMissionControlPort><ClientCommandsPort>0</ClientCommandsPort><AgentIPAddress>127.0.0.1</AgentIPAddress><AgentMissionControlPort>0</AgentMissionControlPort><AgentVideoPort>0</AgentVideoPort><AgentDepthPort>0</AgentDepthPort><AgentLuminancePort>0</AgentLuminancePort><AgentObservationsPort>0</AgentObservationsPort><AgentRewardsPort>0</AgentRewardsPort><AgentColourMapPort>0</AgentColourMapPort></ClientAgentConnection></MissionInit>
50. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:14] [EnvServerSocketHandler/INFO]: [STDOUT]: Setting width, height to 64, 64
51. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:14] [EnvServerSocketHandler/INFO]: [STDOUT]: Gamma: 2.0
52. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:14] [EnvServerSocketHandler/INFO]: [STDOUT]: FOV: 70.0
53. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:14] [EnvServerSocketHandler/INFO]: [STDOUT]: GuiScale: 1.0
54. DEBUG:minerl.env.malmo.instance.eb2501:[15:46:14] [Sound engine/FATAL]: Error executing task on Sound executor
55. ERROR:minerl.env.malmo.instance.eb2501:java.lang.IllegalStateException: Tried to release unknown channel
56. DEBUG:minerl.env.malmo.instance.eb2501: at net.minecraft.client.audio.SoundSystem.release(SoundSystem.java:151) ~[mcprec-6.13.jar:?]
57. DEBUG:minerl.env.malmo.instance.eb2501: at net.minecraft.client.audio.ChannelManager$Entry.release(ChannelManager.java:9DEBUG:minerl.env.malmo.instance.eb2501: at net.minecraft.client.audio.ChannelManager.lambda$tick$3(ChannelManager.java:58) ~[mcprec-6.13.jar:?]
58. DEBUG:minerl.env.malmo.instance.eb2501: at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:DEBUG:minerl.env.malmo.instance.eb2501: at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:109) ~[mcprec-6.13.jar:?]
59. DEBUG:minerl.env.malmo.instance.eb2501: at net.minecraft.util.concurrent.ThreadTaskExecutor.driveUntil(ThreadTaskExecutor.java:119) ~[mcprec-6.13.jar:?]
60. DEBUG:minerl.env.malmo.instance.eb2501: at net.minecraft.client.audio.SoundEngineExecutor.run(SoundEngineExecutor.java:39) ~[mcprec-6.13.jar:?]
61. DEBUG:minerl.env.malmo.instance.eb2501: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
62. 
63. Traceback (most recent call last):
64.   File "<stdin>", line 1, in <module>
65.   File "X:\Code\Conda\lib\site-packages\gym\wrappers\time_limit.py", line 26, in reset
66.     return self.env.reset(**kwargs)
67.   File "X:\Code\Conda\lib\site-packages\gym\wrappers\order_enforcing.py", line 18, in reset
68.     return self.env.reset(**kwargs)
69.   File "X:\Code\Conda\lib\site-packages\minerl\env\_singleagent.py", line 22, in reset
70.     multi_obs = super().reset()
71.   File "X:\Code\Conda\lib\site-packages\minerl\env\_multiagent.py", line 446, in reset
72.     self._send_mission(self.instances[0], agent_xmls[0], self._get_token(0, ep_uid))  # Master
73.   File "X:\Code\Conda\lib\site-packages\minerl\env\_multiagent.py", line 605, in _send_mission
74.     reply = comms.recv_message(instance.client_socket)
75.   File "X:\Code\Conda\lib\site-packages\minerl\env\comms.py", line 63, in recv_message
76.     lengthbuf = recvall(sock, 4)
77.   File "X:\Code\Conda\lib\site-packages\minerl\env\comms.py", line 73, in recvall
78.     newbuf = sock.recv(count)
79. socket.timeout: timed out

**Comment by cdneeee** [comment]
#725 
I know he fixed a similar error by downgrading his Minerl, but is there something else?

**Comment by Miffyli** [comment]
Hmm I can not remember from memory if that audio error the Minecraft instance is throwing out is crucial or can be ignored. This could be result of some weirder audio system on your computer, but I have no idea what could cause it (and in any case, it should not crash the whole thing). The error suggests that the Minecraft instance did die (it did launch correctly first) and Python code dies soon after to timeout.

I would try downgrading, and potentially reinstalling this version. Unfortunately I do not have further tips to give on solving this issue :(

**Comment by cdneeee** [comment]
The fatal audio error happens when my wireless headphones are off, that's not what causing it.
Well downgrading it is I guess, I will try.
I meant some tips and advices going forward, what to do and what not to

One stranger thing is that hello world environment worked without problems, and treechop wouldn't 
Thanks for help tho

**Comment by cdneeee** [comment]
After downgrading to 0.4.4
The minecraft window is Not responding, program execution is stuck at the last line
Having this:
DEBUG:minerl.env.malmo.instance.1b2775:[22:54:20] [Client thread/INFO]: [STDOUT]: Resized the window
DEBUG:minerl.env.malmo.instance.1b2775:[22:54:20] [Client thread/INFO]: [STDOUT]: Unpausing
>>> done = False
>>> while not done:
...     # Take a no-op through the environment.
...     obs, rew, done, _ = env.step(env.action_space.noop())
...     # Do something
...
DEBUG:minerl.env.malmo.instance.1b2775:[22:54:50] [Server thread/INFO]: [STDOUT]: Warning: managed 9/20 ticks this second.
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:30] [Client thread/INFO]: [CHAT] §l28...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:30] [Client thread/INFO]: [CHAT] §l27...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:30] [Client thread/INFO]: [CHAT] §l26...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:30] [Client thread/INFO]: [CHAT] §l25...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:30] [Client thread/INFO]: [CHAT] §l24...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:30] [Client thread/INFO]: [CHAT] §l23...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:30] [Client thread/INFO]: [CHAT] §l22...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:30] [Client thread/INFO]: [CHAT] §l21...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:31] [Client thread/INFO]: [CHAT] §l20...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:31] [Client thread/INFO]: [CHAT] §l19...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:31] [Client thread/INFO]: [CHAT] §l18...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:31] [Client thread/INFO]: [CHAT] §l17...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:31] [Client thread/INFO]: [CHAT] §l16...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:31] [Client thread/INFO]: [CHAT] §l15...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:31] [Client thread/INFO]: [CHAT] §l14...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:31] [Client thread/INFO]: [CHAT] §l13...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:31] [Client thread/INFO]: [CHAT] §l12...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:31] [Client thread/INFO]: [CHAT] §l11...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:31] [Client thread/INFO]: [CHAT] §l10...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [CHAT] §l9...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [CHAT] §l8...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [CHAT] §l7...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [CHAT] §l6...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [CHAT] §c§l5...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [CHAT] §c§l3...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [CHAT] §c§l2...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [CHAT] §c§l1...
>>> DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Server thread/INFO]: [STDOUT]: SERVER request state: WAITING_FOR_AGENTS_TO_QUIT
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Server thread/INFO]: [STDOUT]: SERVER enter state: WAITING_FOR_AGENTS_TO_QUIT
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [CHAT] §c§l0...
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [STDOUT]: SM: [CLIENT_STATE_MACHINE] Mission ended for reason: null world still exists: true
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [STDOUT]: Unpausing
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [STDOUT]: CLIENT request state: MISSION_ENDED
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [STDOUT]: CLIENT enter state: MISSION_ENDED
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [STDOUT]: inform the agent
WARNING:minerl.env.malmo.instance.1b2775:[22:55:32] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6ms behind, skipping 0 tick(s)
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [STDOUT]: CLIENT request state: WAITING_FOR_SERVER_MISSION_END
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [STDOUT]: CLIENT enter state: WAITING_FOR_SERVER_MISSION_END
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Server thread/INFO]: [STDOUT]: SERVER request state: CLEAN_UP
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Server thread/INFO]: [STDOUT]: SERVER enter state: CLEAN_UP
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Server thread/INFO]: [STDOUT]: SERVER request state: DORMANT
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [STDOUT]: CLIENT request state: DORMANT
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [STDOUT]: CLIENT enter state: DORMANT
DEBUG:minerl.env.malmo.instance.1b2775:[22:55:32] [Client thread/INFO]: [STDOUT]: JETTISONING 0 COMMANDS

**Comment by Miffyli** [comment]
That might be expected behaviour, if you are running of the examples, which does not print out anything. The window does not update/show up, and you need to observe what the `obs` variable contains (e.g. show it with opencv's `cv.imshow`), to see what is happening. It should not get stuck at the end, though, and should close gracefully.
