### ISSUE TITLE
CompassAngle of demonstrations seems to be incorrect in Navigate tasks

### ISSUE THREAD

**Issue by phidnight** [minerllabs/minerl#75]
In demonstrations, values of `compassAngle` in Navigate tasks are always non-positive (i.e. in [-180, 0]).
It seems that both -180 and 0 represent the same direction (forward) in demonstrations, which differs from training environments.

Could you check whether current `compassAngle`s of demonstrations and training environments are same or not?

**Comment by brandonhoughton** [comment]
Great find - I will look into this
