### ISSUE TITLE
env.render() issue 

### ISSUE THREAD

**Issue by JoHaYoung227** [minerllabs/minerl#751]
![스크린샷 2024-02-27 032635](https://github.com/minerllabs/minerl/assets/103165774/0cc54782-d882-44fe-88e4-e1abd983a9a0)

It seems that when using the env.render() code, the window appears distorted. I wonder why. Could it be because I'm using a CPU environment without GPU support? Additionally, if I drag the window back and forth, the screen appears correctly. However, it's not practical to keep dragging it to view the screen continuously, so I need a solution.
so I need a solution. Thank you

**Comment by Miffyli** [comment]
Hey. Which OS and system are you using, and which MineRL did you install? This could be an OS level issue, however I have not used "env.render" in a while and something might have gone off in the dependencies.

**Comment by JoHaYoung227** [comment]
I am using a Linux Ubuntu environment, and I'm using version 0.3.7 of MineRL. Thank you.

**Comment by JoHaYoung227** [comment]
I am using a Linux Ubuntu environment, and I'm using version 0.3.7 of MineRL.

**Comment by Miffyli** [comment]
0.3.7 render should work fine, but I have not tried it in a long time. Unfortunately I do not have better suggestions to give other than checking this on another system or using different means to render the images shown in the game (e.g., take the image observation and use opencv2 `cv2.imshow` command).

**Comment by JoHaYoung227** [comment]
Thank you for your response. :)
