### ISSUE TITLE
Why the maven build script still using Minecraft 1.11?

### ISSUE THREAD

**Issue by GF-Huang** [minerllabs/minerl#753]
https://github.com/minerllabs/minerl/blob/8268ee99329ab45793859050d95352d35274532b/minerl/Malmo/Minecraft/build.gradle#L62-L73

**Comment by Miffyli** [comment]
Hey. Malmo side of code is not used in the modern MineRL anymore. The code remained there as it was not cleaned away (IIRC something broke if the folder was deleted).

Edit: You should look at the MCP-Reborn related files for up to date info.
