### ISSUE TITLE
Extreme rewards in NavigateExtremeDense

### ISSUE THREAD

**Issue by marioyc** [minerllabs/minerl#76]
This always seems to happen (for all the players) during the first few steps (about 25)

**Comment by marioyc** [comment]
Some examples:

> r2g1unhappy_peach_horror-6_30375-31338
> Min = -1870.7664794921875 (Frame 0), Max = 766.2726440429688 (Frame 1)
> 
> r2g1mundane_basil_spirit-5_613-2087
> Min = -213.39503479003906 (Frame 0), Max = 119.181884765625 (Frame 1)
> 
> r2g1svelte_cherry_devil-9_12325-18430
> Min = -881.9906005859375 (Frame 1), Max = 1654.2091064453125 (Frame 0)
> 
> r2g1frozen_date_godzilla-7_8231-9437
> Min = -1140.654296875 (Frame 1), Max = 1140.654296875 (Frame 2)
> 
> r2g1subtle_iceberg_lettuce_nymph-4_28719-32356
> Min = -851.4783935546875 (Frame 1), Max = 284.9634094238281 (Frame 2)

**Comment by brandonhoughton** [comment]
Thanks - looking into this
