### ISSUE TITLE
problems while installing minerl 

### ISSUE THREAD

**Issue by sramichetty20019** [minerllabs/minerl#760]
Hello everyone I am trying to install Minerl on my system, OS: Ubuntu 22, I initiated the entire process in the conda environment, 
However I am getting the following error, I believe the error is related to the gym package, I tried to install the gym package from the source but I am still getting the same error 
Below is the screenshot of the error : 
![Screenshot 2024-04-10 at 9 16 55 AM](https://github.com/minerllabs/minerl/assets/114448089/9d15f787-8d5a-4df4-8f49-21aecbb340ef)
It would be helpful to know the correct way to install minerl package, and the steps involved
Thank you in advance

**Comment by Miffyli** [comment]
Hey. Indeed this is probably an issue with the gym package. Unfortunately the pypi version of v0.4.4 has requirement for Gym that does not work with modern Python (and base package) versions nicely. I would recommend installing MineRL from github (see instructions in the main readme), which should work fine.

**Comment by sramichetty20019** [comment]
Thank you the installation issue got resolved . It was just the problem with gym package,doing a clean install worked for me
