### ISSUE TITLE
Minecraft window continuously reopens and is set to the active foreground window. Obs['pov'] is black

### ISSUE THREAD

**Issue by liquidnode** [minerllabs/minerl#77]
After a significant fps drop (i.e. the user does not run env.step for a short duration, for example to save the current model), the window starts to being continuously reopened every time env.step is executed while also being reset to the active foreground window, so it is no longer possible to change to a different window other than minecraft.

This wouldn't be much of a problem if the returned obs['pov'] wouldn't be black/equal to np.zeros after the fps drop occurs. When the minecraft window is inspected, one can see that during the continuous reopening of the window, the enviroment is not rendered/the screen is black except for the health/inventory bar/messages and the rendering of the active right hand minecraft item.

I'm working on Windows 10. It could be that this is a Windows only problem.

**Comment by MadcowD** [comment]
It is a windows problem! I'm going to investigate and solve this.

Are you on the latest version?
```
pip3 install --upgrade minerl
```

**Comment by MadcowD** [comment]
Oh your actual minecraft game has a black screen itself?

**Comment by liquidnode** [comment]
It's not entirely black, for example the health bar is still visible. Only the enviroment rendering is black after env.step isn't called for a while. I think it is connected to the minecraft window going into the freeze/not responding mode on Windows when it is not refreshed for a while. I think an easy way to solve this issue is to continue render minecraft every 100 or so ms even when no env.step is called.

**Comment by liquidnode** [comment]
> 
> 
> It is a windows problem! I'm going to investigate and solve this.
> 
> Are you on the latest version?
> 
> ```
> pip3 install --upgrade minerl
> ```

Yes I'm on the latest minerl version

**Comment by MadcowD** [comment]
Wow great insight! (This is one of the negatives of developing this on Linux) I'll see if we can do some sort of windows keep alive.

**Comment by MadcowD** [comment]
Does it stop being black after you step normally?

**Comment by liquidnode** [comment]
> 
> 
> Does it stop being black after you step normally?

No it does not.

**Comment by liquidnode** [comment]
I've found a workaround by increasing the HungAppTimeout variable in regedit.

**Comment by MadcowD** [comment]
Okay this is awesome!

**Comment by MadcowD** [comment]
I was able to fix this using your information! This will be available in the next release of MineRL.
