### ISSUE TITLE
Build Failure: Could not find com.github.SpongePowered:MixinGradle

### ISSUE THREAD

**Issue by JP-Kaiser** [minerllabs/minerl#790]
Issue Description:
 
I'm encountering (when i run "pip install git+https://github.com/minerllabs/minerl") a build failure when attempting to configure the root project 'Minecraft'. The build fails with the following exception:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Minecraft'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.SpongePowered:MixinGradle:dcfaf61.
     Searched in the following locations:
       - https://jitpack.io/com/github/SpongePowered/MixinGradle/dcfaf61/MixinGradle-dcfaf61.pom
       - https://jitpack.io/com/github/SpongePowered/MixinGradle/dcfaf61/MixinGradle-dcfaf61.jar
       - https://jcenter.bintray.com/com/github/SpongePowered/MixinGradle/dcfaf61/MixinGradle-dcfaf61.pom
       - https://jcenter.bintray.com/com/github/SpongePowered/MixinGradle/dcfaf61/MixinGradle-dcfaf61.jar
       - https://repo.maven.apache.org/maven2/com/github/SpongePowered/MixinGradle/dcfaf61/MixinGradle-dcfaf61.pom
       - https://repo.maven.apache.org/maven2/com/github/SpongePowered/MixinGradle/dcfaf61/MixinGradle-dcfaf61.jar
       - https://maven.minecraftforge.net/com/github/SpongePowered/MixinGradle/dcfaf61/MixinGradle-dcfaf61.pom
       - https://maven.minecraftforge.net/com/github/SpongePowered/MixinGradle/dcfaf61/MixinGradle-dcfaf61.jar
       - https://oss.sonatype.org/content/repositories/snapshots/com/github/SpongePowered/MixinGradle/dcfaf61/MixinGradle-dcfaf61.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/github/SpongePowered/MixinGradle/dcfaf61.jar
       - https://plugins.gradle.org/m2/com/github/SpongePowered/MixinGradle/dcfaf61/MixinGradle-dcfaf61.pom
       - https://plugins.gradle.org/m2/com/github/SpongePowered/MixinGradle/dcfaf61.jar

Steps Taken:

1. Verified that all dependencies and repositories are properly configured in my build script.
2. Checked the availability of MixinGradle:dcfaf61 on the listed repositories, but it seems that this specific version or commit (dcfaf61) is not available.
3. Attempted to update or downgrade related dependencies in case of compatibility issues.
4. Deactivated and reactivated my Conda environment to ensure the correct Python environment was being used, as this project involves Python dependencies as well.

**Comment by lukedoma1** [comment]
why was this closed? I am having the same issue
