### ISSUE TITLE
`iron_axe` action is missing for MineRLObtainDiamond-v0

### ISSUE THREAD

**Issue by keisuke-nakata** [minerllabs/minerl#89]
I'm not sure this is intended or not, but for `MineRLObtainDiamond-v0` env, there is no `iron_axe` action for `equip` and `nearbyCraft`.

**Comment by MadcowD** [comment]
Happy to add this; if you'd be willing to make a PR for this that'd be useful.

**Comment by keisuke-nakata** [comment]
I have a small question:  
Are the action spaces for all `Obtain`-like envs same?

**Comment by MadcowD** [comment]
(They may well be but I haven't confirmed this)

**Comment by MadcowD** [comment]
@brandonhoughton sanity check>

**Comment by keisuke-nakata** [comment]
see #91
