### ISSUE TITLE
The observation space seems inccorrect

### ISSUE THREAD

**Issue by chenjunjie1994** [minerllabs/minerl#95]
Hi,

I run the code as follows 

=======================================
    env = gym.make("MineRLObtainDiamond-v0") 
    obs, _ = env.reset()
    print (obs)
=======================================

Then I got 

=======================================
{'pov': array([[[114, 156, 235],
        [114, 156, 235],
        [114, 156, 235],
        ...,
        [114, 156, 235],
        [114, 156, 235],
        [114, 156, 235]],

       [[114, 156, 235],
        [114, 156, 235],
        [114, 156, 235],
        ...,
        [114, 156, 235],
        [114, 156, 235],
        [114, 156, 235]],

       [[114, 156, 234],
        [114, 156, 234],
        [114, 156, 234],
        ...,
        [114, 156, 234],
        [114, 156, 234],
        [114, 156, 234]],

       ...,

       [[ 78, 101,  48],
        [ 92, 118,  57],
        [ 91, 117,  56],
        ...,
        [ 84, 109,  53],
        [ 81, 104,  51],
        [ 81, 104,  51]],

       [[ 92, 119,  57],
        [ 91, 117,  56],
        [ 91, 117,  56],
        ...,
        [ 84, 109,  53],
        [ 84, 109,  53],
        [ 84, 109,  53]],

       [[ 81, 104,  50],
        [ 81, 104,  50],
        [ 74,  96,  46],
        ...,
        [ 77,  99,  48],
        [ 84, 109,  53],
        [ 84, 109,  53]]], dtype=uint8), 'equipped_items': {'mainhand': {}, 'offhand': {}}, 'inventory': {'coal': 0, 'cobblestone': 0, 'crafting_table': 0, 'dirt': 0, 'furnace': 0, 'iron_axe': 0, 'iron_ingot': 0, 'iron_ore': 0, 'iron_pickaxe': 0, 'log': 0, 'planks': 0, 'stick': 0, 'stone': 0, 'stone_axe': 0, 'stone_pickaxe': 0, 'torch': 0, 'wooden_axe': 0, 'wooden_pickaxe': 0}}
==============================================

As stated in the documentation, the "equipped_items" entry should have structure like 
===========
    "equipped_items": {
            "mainhand": {
                    "damage": "Box(1,)",
                    "maxDamage": "Box(1,)",
                    "type": "Enum(none,wooden_axe,wooden_pickaxe,stone_axe,stone_pickaxe,iron_pickaxe,other)"
            }
    },
====================

But here it shows 'equipped_items': {'mainhand': {}, 'offhand': {}}, which seems incorrect. 

How can I get the "equipped_items" entry as stated in the documentation ?

Thanks.

**Comment by MadcowD** [comment]
Ah good catch, I'll make sure that it selects none if its none.

**Comment by MadcowD** [comment]
@chenjunjie1994  This was fixed! Make sure to upgrade to `minerl` v`0.1.15`!
```
pip3 install --upgrade minerl
```
